// swift-tools-version: 6.0
import PackageDescription

// The pure-logic half of the iOS client: stream parsing, wire models, request building.
//
// It is deliberately Foundation-only and imports no UI framework, so it compiles and tests
// on Linux. That matters because the streaming wire format is hand-rolled and full of
// edge cases (rollback markers, split tags, UTF-16 offsets) that are far cheaper to pin
// down with tests than to debug on a device.
//
// The Xcode app target compiles these same files directly (see project.yml), so nothing
// here needs `public` access.
let package = Package(
    name: "EmperorCore",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "EmperorCore", targets: ["EmperorCore"]),
    ],
    targets: [
        .target(name: "EmperorCore"),
        // The golden fixtures for the tool prompts, carried over from the Android client. They
        // were generated by running the platform's own JavaScript under Node and capturing the
        // output, so they pin this port against the real thing rather than against anyone's
        // reading of it. Copied verbatim — they are the reference, not an input.
        .testTarget(
            name: "EmperorCoreTests",
            dependencies: ["EmperorCore"],
            resources: [
                .copy("Resources/tools"),
                .copy("Resources/cards"),
                .copy("Resources/tool-cases.json"),
                // Answers run through the platform's `citations.js` under Node; see
                // `scripts/generate-citation-fixtures.mjs`.
                .copy("Resources/citations.json"),
                // The platform's phone rules, run under Node; see `scripts/generate-phone-fixtures.mjs`.
                .copy("Resources/phone.json"),
                // The Document Utilities' rules — page order, the size searches, the layouts —
                // generated from the platform by `scripts/generate-file-tool-fixtures.mjs`.
                .copy("Resources/file-tools"),
            ]),
    ]
)
