// Generated by scripts/generate-litigator-fixtures.mjs from the platform's own modules — do not
// edit by hand.
//
// Produced by evaluating src/roles/roleConfig.js, src/roles/litigatorDrafting.js,
// src/roles/litigatorForms.js and src/tools/registry.js under Node. If the taxonomy changes on the
// platform, regenerate this file and its fixtures rather than editing either to match: the fixture
// is the contract and this is the copy. The resolvers that read it are hand-ported, in
// LitigatorDrafting.swift.

import Foundation

/// The matters the Litigator workspace offers, in the platform's order — Civil, Criminal, then the
/// practice areas (`roleConfig.js`, the litigator entry's `matters`). The one-line summaries are
/// `LitigatorMatter.jsx`'s `META`, which describes Civil and Criminal only.
let LITIGATOR_MATTERS: [LitigatorMatter] = [
    LitigatorMatter(id: "civil", label: "Civil", summary: "Suits, writs, appeals, execution and tribunal matters."),
    LitigatorMatter(id: "criminal", label: "Criminal", summary: "FIR/complaint cases, cheque bounce, bail, appeals and revisions."),
    LitigatorMatter(id: "ipr", label: "IPR", short: "IPR"),
    LitigatorMatter(id: "tax", label: "Tax", short: "Tax"),
    LitigatorMatter(id: "banking", label: "Banking & Insolvency", short: "Banking"),
    LitigatorMatter(id: "arbitration", label: "Arbitration", short: "Arbitration"),
    LitigatorMatter(id: "cyber", label: "Cyber & Data Protection", short: "Cyber"),
    LitigatorMatter(id: "labour", label: "Labour & Employment Protection", short: "Labour"),
    LitigatorMatter(id: "property", label: "Property & Real Estate", short: "Property"),
    LitigatorMatter(id: "company", label: "Corporate & Company", short: "Corporate"),
    LitigatorMatter(id: "constitutional", label: "Administrative & Constitutional", short: "Constitutional"),
    LitigatorMatter(id: "international", label: "International Law", short: "International"),
]

/// The proceeding (case type) a Civil or Criminal matter can be narrowed to — `PROCEEDINGS`.
/// It gates the Issues section and the two trial sections; the practice areas have none.
let LITIGATOR_PROCEEDINGS: [String: [String]] = [
    "civil": ["Suit", "Writ petition", "Appeal", "Execution", "Tribunal / special forum"],
    "criminal": ["State (police/FIR) case", "Private complaint", "Cheque bounce (NI s.138)", "Appeal / revision", "Bail matter"],
]

/// Civil and Criminal's sections — `DRAFT_SECTIONS`. One list for both: each document carries
/// the branch it belongs to, and a section shows for a matter if any of its documents does.
let LITIGATOR_DRAFT_SECTIONS: [LitigatorSection] = [
    LitigatorSection(
        key: "initiating", title: "Pleadings & Petitions",
        items: [
            LitigatorItem(id: "plaint", label: "Plaint (suit, Order 7)", branch: .civil),
            LitigatorItem(id: "writ", label: "Writ petition (Art. 226/227)", branch: .civil, note: "with synopsis + list of dates"),
            LitigatorItem(id: "memo-appeal", label: "Memorandum of appeal (Order 41)", branch: .civil),
            LitigatorItem(id: "execution-petition", label: "Execution petition (Order 21)", branch: .civil),
            LitigatorItem(id: "tribunal-petition", label: "Petition / complaint (tribunal, consumer, NCLT, family)", branch: .civil),
        ]),
    LitigatorSection(
        key: "complaints", title: "Complaint & Institution", template: "criminal-complaint",
        draftInstruction: "Draft the criminal-institution document: a private complaint (BNSS 223), an application u/s 175(3) BNSS to direct investigation, a s.138 NI Act complaint, a protest petition, or an FIR / Zero-FIR representation — setting out the parties, the statutory notice and cause of action where applicable, the ingredients of the offence, and the relief; verify and support by affidavit.",
        items: [
            LitigatorItem(id: "private-complaint", label: "Private complaint to Magistrate (BNSS 223, old 200)", branch: .criminal),
            LitigatorItem(id: "app-175", label: "Application u/s 175(3) BNSS to direct FIR / investigation (old 156(3))", branch: .criminal),
            LitigatorItem(id: "ni138-complaint", label: "NI s.138 complaint (cheque bounce)", branch: .criminal),
            LitigatorItem(id: "protest-petition", label: "Protest petition", branch: .criminal),
            LitigatorItem(id: "fir-representation", label: "FIR / Zero FIR representation", branch: .criminal),
        ]),
    LitigatorSection(
        key: "reply", title: "Reply / responsive pleading",
        items: [
            LitigatorItem(id: "written-statement", label: "Written statement (Order 8)", branch: .civil),
            LitigatorItem(id: "counter-claim", label: "Counter-claim / set-off", branch: .civil),
            LitigatorItem(id: "rejoinder", label: "Rejoinder / replication", branch: .civil),
            LitigatorItem(id: "counter-affidavit", label: "Counter-affidavit (writ)", branch: .civil),
            LitigatorItem(id: "rejoinder-affidavit", label: "Rejoinder-affidavit (writ)", branch: .civil),
            LitigatorItem(id: "cross-objections", label: "Cross-objections (appeal, Order 41 R22)", branch: .civil),
            LitigatorItem(id: "exec-objections", label: "Objections / reply (execution)", branch: .civil),
        ]),
    LitigatorSection(
        key: "issues", title: "Issues", gate: .issues,
        items: [
            LitigatorItem(id: "draft-issues", label: "Draft / proposed issues", branch: .civil),
        ]),
    LitigatorSection(
        key: "bail", title: "Bail",
        items: [
            LitigatorItem(id: "anticipatory-bail", label: "Anticipatory bail (BNSS 482, old 438) — Sessions / HC", branch: .criminal),
            LitigatorItem(id: "regular-bail-magistrate", label: "Regular bail before Magistrate (BNSS 480, old 437)", branch: .criminal),
            LitigatorItem(id: "bail-sessions-hc", label: "Bail before Sessions / HC (BNSS 483, old 439)", branch: .criminal),
            LitigatorItem(id: "bailable-bail", label: "Bail in bailable offence (BNSS 478, old 436)", branch: .criminal),
            LitigatorItem(id: "default-bail", label: "Default / statutory bail", branch: .criminal),
            LitigatorItem(id: "interim-bail", label: "Interim bail", branch: .criminal),
            LitigatorItem(id: "bail-reply", label: "Reply / objections to bail (prosecution)", branch: .criminal),
            LitigatorItem(id: "bail-cancellation", label: "Bail cancellation", branch: .criminal),
            LitigatorItem(id: "surety-affidavit", label: "Surety affidavit / bail bond", branch: .criminal),
        ]),
    LitigatorSection(
        key: "evidence", title: "Evidence", gate: .trial,
        items: [
            LitigatorItem(id: "evidence-affidavit-c", label: "Evidence affidavit — examination-in-chief (Order 18 R4)", branch: .civil),
            LitigatorItem(id: "witness-list-c", label: "List of witnesses (Order 16)", branch: .civil),
            LitigatorItem(id: "doc-index-c", label: "List / index of documents", branch: .civil),
            LitigatorItem(id: "summon-app-c", label: "Application to summon witness / produce documents", branch: .civil),
            LitigatorItem(id: "evidence-affidavit-cr", label: "Evidence affidavit — complainant's evidence (NI Act s.145)", branch: .criminal),
            LitigatorItem(id: "witness-list-cr", label: "List of witnesses / documents", branch: .criminal),
            LitigatorItem(id: "exam-chief-notes-cr", label: "Examination-in-chief notes", branch: .criminal),
            LitigatorItem(id: "summon-app-cr", label: "Application to summon witness / produce document", branch: .criminal),
        ]),
    LitigatorSection(
        key: "cross", title: "Cross-examination", gate: .trial,
        items: [
            LitigatorItem(id: "cross-pw", label: "Cross questions — plaintiff / prosecution witnesses (PW1, PW2 …)", branch: .both),
            LitigatorItem(id: "cross-dw", label: "Cross questions — defendant / defence witnesses (DW1, DW2 …)", branch: .both),
            LitigatorItem(id: "re-exam-notes", label: "Re-examination notes", branch: .civil),
            LitigatorItem(id: "accused-statement", label: "Statement of accused — prep notes (BNSS 351, old 313)", branch: .criminal),
        ]),
    LitigatorSection(
        key: "arguments", title: "Arguments",
        items: [
            LitigatorItem(id: "oral-args", label: "Oral argument notes", branch: .both),
            LitigatorItem(id: "written-args", label: "Written arguments / submissions", branch: .both),
            LitigatorItem(id: "list-authorities", label: "List of authorities", branch: .both),
            LitigatorItem(id: "args-charge-sentence", label: "Arguments on charge / on sentence", branch: .criminal),
        ]),
    LitigatorSection(
        key: "applications", title: "Applications — interlocutory",
        items: [
            LitigatorItem(id: "interim-injunction", label: "Interim injunction (Order 39 R1 & 2)", branch: .civil),
            LitigatorItem(id: "amendment", label: "Amendment of pleadings (Order 6 R17)", branch: .civil),
            LitigatorItem(id: "condonation-delay", label: "Condonation of delay", branch: .civil),
            LitigatorItem(id: "inherent-151", label: "Inherent powers (Sec. 151 CPC)", branch: .civil),
            LitigatorItem(id: "production-discovery", label: "Production / discovery (Order 11)", branch: .civil),
            LitigatorItem(id: "implead", label: "Implead / add or delete party (Order 1 R10)", branch: .civil),
            LitigatorItem(id: "interim-stay", label: "Interim relief / stay", branch: .civil),
            LitigatorItem(id: "restoration-exparte", label: "Restoration / set aside ex-parte (Order 9)", branch: .civil),
            LitigatorItem(id: "compromise-terms", label: "Compromise / consent terms (Order 23 R3)", branch: .civil),
            LitigatorItem(id: "reply-application-c", label: "Reply / objections to an application", branch: .civil),
            LitigatorItem(id: "discharge", label: "Discharge application (BNSS 250 / 262 / 263)", branch: .criminal),
            LitigatorItem(id: "supply-docs", label: "Supply of documents / copies (BNSS 230, old 207)", branch: .criminal),
            LitigatorItem(id: "quashing", label: "Quashing petition — HC inherent powers (BNSS 528, old 482)", branch: .criminal),
            LitigatorItem(id: "exemption-appearance", label: "Exemption from personal appearance", branch: .criminal),
            LitigatorItem(id: "further-investigation", label: "Further investigation / additional documents", branch: .criminal),
            LitigatorItem(id: "recall-witness", label: "Recall of witness / additional evidence", branch: .criminal),
            LitigatorItem(id: "transfer-app", label: "Transfer application", branch: .criminal),
            LitigatorItem(id: "condonation-restoration-cr", label: "Condonation / restoration", branch: .criminal),
            LitigatorItem(id: "reply-application-cr", label: "Reply / objections to an application", branch: .criminal),
        ]),
    LitigatorSection(
        key: "civil-appeals", title: "Appeals, Revision & Review", template: "civil-appeal",
        draftInstruction: "Draft the appellate / review document: a second appeal on a substantial question of law (s.100 CPC), a civil revision (s.115 CPC), or a review (Order 47 Rule 1 CPC) — with the particulars of the impugned judgment / decree (court, number, date), the limitation position and condonation if required, numbered grounds, and the specific relief; for a second appeal, frame the substantial question(s) of law.",
        items: [
            LitigatorItem(id: "second-appeal", label: "Second appeal (s.100 CPC)", branch: .civil),
            LitigatorItem(id: "civil-revision", label: "Civil revision (s.115 CPC)", branch: .civil),
            LitigatorItem(id: "review-petition", label: "Review (Order 47 R1 CPC)", branch: .civil),
        ]),
    LitigatorSection(
        key: "post-trial", title: "Post-trial / appellate",
        items: [
            LitigatorItem(id: "appeal-conviction", label: "Appeal against conviction (accused)", branch: .criminal),
            LitigatorItem(id: "appeal-acquittal", label: "Appeal against acquittal / victim's appeal (BNSS 413, old 372 proviso)", branch: .criminal),
            LitigatorItem(id: "revision", label: "Revision (BNSS 438, old 397)", branch: .criminal),
            LitigatorItem(id: "suspension-sentence", label: "Suspension of sentence & bail pending appeal (BNSS 430, old 389)", branch: .criminal),
            LitigatorItem(id: "quashing-post", label: "Quashing (BNSS 528, old 482)", branch: .criminal),
            LitigatorItem(id: "plea-bargaining", label: "Plea bargaining", branch: .criminal),
            LitigatorItem(id: "probation-mitigation", label: "Probation / sentence-mitigation submissions", branch: .criminal),
        ]),
    LitigatorSection(
        key: "common", title: "Common documents",
        items: [
            LitigatorItem(id: "vakalatnama", label: "Vakalatnama", branch: .both),
            LitigatorItem(id: "memo-parties", label: "Memo of parties", branch: .both),
            LitigatorItem(id: "affidavit", label: "Affidavit / verification", branch: .both),
            LitigatorItem(id: "legal-notice", label: "Legal / demand notice (incl. NI s.138 statutory notice)", branch: .both),
            LitigatorItem(id: "certified-copies", label: "Application for certified copies", branch: .both),
            LitigatorItem(id: "caveat", label: "Caveat (s.148A CPC)", branch: .civil),
            LitigatorItem(id: "surety-docs", label: "Surety documents / bail bonds", branch: .criminal),
        ]),
]

/// The practice areas — `AREAS` — each with its own sections, documents and governing-law note.
/// Keyed by matter id.
let LITIGATOR_AREAS: [String: LitigatorArea] = [
    "arbitration": LitigatorArea(
        label: "Arbitration",
        codeNote: "Apply the Arbitration and Conciliation Act, 1996 (as amended) and any applicable institutional rules (SIAC / ICC / MCIA / DIAC).",
        sections: [
            LitigatorSection(
                key: "invocation", title: "Invocation & Reference", template: "arbitration-notice",
                draftInstruction: "Draft the notice invoking arbitration (s.21) or the application for appointment of arbitrator (s.11): identify the arbitration agreement and the disputes, the claimant's nomination, and (for s.11) the failure of the agreed procedure; seek reference/appointment.",
                items: [
                    LitigatorItem(id: "arb-s21-notice", label: "Notice invoking arbitration (s.21)"),
                    LitigatorItem(id: "arb-s11", label: "Application for appointment of arbitrator (s.11)"),
                    LitigatorItem(id: "arb-nomination", label: "Nomination / constitution of tribunal"),
                ]),
            LitigatorSection(
                key: "interim", title: "Interim Measures", template: "arbitration-petition",
                draftInstruction: "Draft the interim-measures application under s.9 (court) or s.17 (tribunal): set out the arbitration agreement and the urgency, and plead a prima facie case, balance of convenience and irreparable injury; pray for the specific protective order.",
                items: [
                    LitigatorItem(id: "arb-s9", label: "Petition for interim measures (s.9)"),
                    LitigatorItem(id: "arb-s17", label: "Application for interim measures before tribunal (s.17)"),
                    LitigatorItem(id: "arb-emergency", label: "Emergency-arbitrator application"),
                ]),
            LitigatorSection(
                key: "pleadings", title: "Pleadings", template: "arbitration-pleadings",
                draftInstruction: "Draft the pleading with the parties, the agreement and the seat, the facts, the issues and the reliefs with quantification; for a Redfern schedule, tabulate the documents sought, their relevance and the objections.",
                items: [
                    LitigatorItem(id: "arb-soc", label: "Statement of Claim"),
                    LitigatorItem(id: "arb-sod", label: "Statement of Defence"),
                    LitigatorItem(id: "arb-counterclaim", label: "Counterclaim"),
                    LitigatorItem(id: "arb-rejoinder", label: "Rejoinder"),
                    LitigatorItem(id: "arb-issues", label: "List of issues"),
                    LitigatorItem(id: "arb-redfern", label: "Redfern schedule (document production)"),
                ]),
            LitigatorSection(
                key: "challenge", title: "Challenge & Enforcement", template: "arbitration-petition",
                draftInstruction: "Draft the s.34 petition to set aside, s.37 appeal, or enforcement under s.36 / s.48 (foreign award): confine s.34 to the statutory grounds (incl. patent illegality for domestic awards) without inviting a merits review; for enforcement, plead finality and the absence of a subsisting stay.",
                items: [
                    LitigatorItem(id: "arb-s34", label: "Petition to set aside award (s.34)"),
                    LitigatorItem(id: "arb-s37", label: "Appeal (s.37)"),
                    LitigatorItem(id: "arb-s36", label: "Enforcement of award (s.36)"),
                    LitigatorItem(id: "arb-s48", label: "Enforcement of foreign award (s.48)"),
                ]),
        ]),
    "tax": LitigatorArea(
        label: "Tax",
        codeNote: "Apply the CGST/IGST Acts and the Income-tax Act, 1961 and the rules made thereunder; cite the exact provision and CBIC/CBDT position.",
        sections: [
            LitigatorSection(
                key: "gst", title: "GST", template: "tax-document",
                draftInstruction: "Draft the GST reply/appeal: a reply to the show-cause notice under s.73/74 CGST Act (DRC-01) addressing each allegation, limitation and quantification; or an appeal to the Appellate Authority (s.107) with grounds and pre-deposit.",
                items: [
                    LitigatorItem(id: "tax-scn-reply", label: "Reply to SCN (s.73/74, DRC-01)"),
                    LitigatorItem(id: "tax-gst-appeal", label: "Appeal to Appellate Authority (s.107)"),
                    LitigatorItem(id: "tax-gst-writ", label: "Writ against GST action"),
                ]),
            LitigatorSection(
                key: "directtax", title: "Direct Tax", template: "tax-document",
                draftInstruction: "Draft the income-tax submission: a reply to the notice (s.142(1)/143(2)/148), an appeal to CIT(A) or ITAT with a statement of facts and grounds, or DRP objections — addressing each addition with law and evidence.",
                items: [
                    LitigatorItem(id: "tax-notice-reply", label: "Reply to notice (s.142(1)/143(2)/148)"),
                    LitigatorItem(id: "tax-cita", label: "Appeal to CIT(A)"),
                    LitigatorItem(id: "tax-itat", label: "Appeal to ITAT"),
                    LitigatorItem(id: "tax-drp", label: "DRP objections"),
                ]),
            LitigatorSection(
                key: "taxremedy", title: "Writs, Stay & Advance Ruling", template: "tax-document",
                draftInstruction: "Draft the writ (where the alternative remedy does not bar it — jurisdiction / natural justice), the stay application pending appeal, the advance-ruling application, or a rectification/refund application — with the governing provision and relief.",
                items: [
                    LitigatorItem(id: "tax-writ", label: "Writ petition (tax)"),
                    LitigatorItem(id: "tax-stay", label: "Stay application"),
                    LitigatorItem(id: "tax-ar", label: "Advance-ruling application"),
                    LitigatorItem(id: "tax-rectification", label: "Rectification / refund application"),
                ]),
        ]),
    "banking": LitigatorArea(
        label: "Banking & Insolvency",
        codeNote: "Apply the Insolvency and Bankruptcy Code, 2016, the SARFAESI Act, 2002 and the RDB Act, 1993, with the IBBI Regulations and the NCLT/DRT rules.",
        sections: [
            LitigatorSection(
                key: "cirp", title: "Insolvency Initiation", template: "ibc-application",
                draftInstruction: "Draft the IBC application: the s.8 demand notice, or the s.7 (financial creditor, Form 1), s.9 (operational creditor, Form 5) or s.10 application — pleading the debt, the default and its date, and the completeness of the form.",
                items: [
                    LitigatorItem(id: "ibc-s8", label: "Demand notice (s.8)"),
                    LitigatorItem(id: "ibc-s7", label: "Financial-creditor application (s.7, Form 1)"),
                    LitigatorItem(id: "ibc-s9", label: "Operational-creditor application (s.9, Form 5)"),
                    LitigatorItem(id: "ibc-s10", label: "Corporate-applicant application (s.10)"),
                ]),
            LitigatorSection(
                key: "cirp-apps", title: "CIRP Applications", template: "ibc-application",
                draftInstruction: "Draft the CIRP application before the Adjudicating Authority: an avoidance application (s.43/45/50/66), a relief/direction, or a CoC / resolution-plan document — citing the section and the record.",
                items: [
                    LitigatorItem(id: "ibc-avoidance", label: "Avoidance application (s.43/45/50/66)"),
                    LitigatorItem(id: "ibc-ia", label: "Interlocutory application (NCLT)"),
                    LitigatorItem(id: "ibc-nclat", label: "Appeal to NCLAT (s.61)"),
                ]),
            LitigatorSection(
                key: "recovery", title: "SARFAESI & Debt Recovery", template: "ibc-application",
                draftInstruction: "Draft the SARFAESI / DRT document: a s.13(4) measure or a s.17 application before the DRT, or an Original Application for recovery — pleading the debt, the security interest and the default.",
                items: [
                    LitigatorItem(id: "sarfaesi-s13", label: "SARFAESI s.13(4) measure"),
                    LitigatorItem(id: "drt-s17", label: "Securitisation application (DRT, s.17)"),
                    LitigatorItem(id: "drt-oa", label: "Original Application (DRT recovery)"),
                ]),
        ]),
    "constitutional": LitigatorArea(
        label: "Administrative & Constitutional",
        codeNote: "Apply the Constitution of India (Arts. 32, 136, 226, 227) and the settled principles of judicial review and administrative law.",
        sections: [
            LitigatorSection(
                key: "writs", title: "Writs", template: "petition",
                draftInstruction: "Draft the writ under Art. 226/227 (or Art. 32): prefix a synopsis and list of dates; plead the fundamental/legal right, the public duty and its breach, the absence of an efficacious alternative remedy, and the specific writ (mandamus / certiorari / prohibition / quo warranto / habeas corpus) prayed for.",
                items: [
                    LitigatorItem(id: "writ-226", label: "Writ petition (Art. 226/227)"),
                    LitigatorItem(id: "writ-32", label: "Writ petition (Art. 32)"),
                    LitigatorItem(id: "writ-habeas", label: "Habeas corpus petition"),
                ]),
            LitigatorSection(
                key: "apex", title: "Supreme Court", template: "petition",
                draftInstruction: "Draft the Supreme Court filing: an SLP (Art. 136) framing the questions of law warranting interference, a review or curative petition, or a transfer petition — with the impugned order, limitation and grounds.",
                items: [
                    LitigatorItem(id: "slp-c", label: "SLP (Civil) — Art. 136"),
                    LitigatorItem(id: "slp-cr", label: "SLP (Criminal) — Art. 136"),
                    LitigatorItem(id: "review-pet", label: "Review petition"),
                    LitigatorItem(id: "curative-pet", label: "Curative petition"),
                    LitigatorItem(id: "transfer-pet", label: "Transfer petition"),
                ]),
            LitigatorSection(
                key: "responsive", title: "Affidavits & Reply", template: "petition",
                draftInstruction: "Draft the counter-affidavit / rejoinder-affidavit to a writ: the preliminary objections (maintainability, laches, alternative remedy), a para-wise reply, and the supporting affidavit.",
                items: [
                    LitigatorItem(id: "writ-counter", label: "Counter-affidavit"),
                    LitigatorItem(id: "writ-rejoinder", label: "Rejoinder-affidavit"),
                ]),
            LitigatorSection(
                key: "pil", title: "Public Interest", template: "pil",
                draftInstruction: "Draft the PIL as drafting support for counsel to settle: establish locus and bona fides, the public interest and the affected class, the facts and the constitutional provisions, and the relief.",
                items: [
                    LitigatorItem(id: "pil-sc", label: "PIL — Supreme Court (Art. 32)"),
                    LitigatorItem(id: "pil-hc", label: "PIL — High Court (Art. 226)"),
                ]),
        ]),
    "ipr": LitigatorArea(
        label: "IPR",
        codeNote: "Apply the Trade Marks Act 1999, the Patents Act 1970, the Copyright Act 1957 and the Designs Act 2000, with the CPC and the Commercial Courts Act / IPD rules.",
        sections: [
            LitigatorSection(
                key: "ip-suits", title: "Infringement Suits", template: "plaint",
                draftInstruction: "Draft the infringement / passing-off suit: plead the plaintiff's title to the mark/patent/copyright/design, the defendant's infringing acts, jurisdiction (incl. s.134 TM Act / s.62 Copyright Act), and the reliefs (injunction, damages / account of profits, delivery-up).",
                items: [
                    LitigatorItem(id: "ip-infringement", label: "Infringement suit"),
                    LitigatorItem(id: "ip-passing-off", label: "Passing-off suit"),
                ]),
            LitigatorSection(
                key: "ip-interim", title: "Interim Relief", template: "interlocutory-application",
                draftInstruction: "Draft the interim application: an Order 39 R1&2 injunction (or a John Doe / Ashok Kumar order), pleading a prima facie case, balance of convenience and irreparable injury; for a s.124 TM Act stay, plead the pending rectification.",
                items: [
                    LitigatorItem(id: "ip-injunction", label: "Order 39 injunction"),
                    LitigatorItem(id: "ip-johndoe", label: "John Doe / Ashok Kumar order"),
                    LitigatorItem(id: "ip-s124-stay", label: "Stay pending rectification (s.124 TM Act)"),
                ]),
            LitigatorSection(
                key: "ip-prosecution", title: "Prosecution & Opposition", template: "ip-prosecution",
                draftInstruction: "Draft the Registry document: a trademark / patent / copyright / design application, a reply to the examination report, or a notice of opposition / rectification — in the prescribed form and format.",
                items: [
                    LitigatorItem(id: "ip-tm-application", label: "Trademark application"),
                    LitigatorItem(id: "ip-exam-reply", label: "Reply to examination report"),
                    LitigatorItem(id: "ip-opposition", label: "Opposition / rectification"),
                ]),
        ]),
    "property": LitigatorArea(
        label: "Property & Real Estate",
        codeNote: "Apply the Transfer of Property Act 1882, the Specific Relief Act 1963, the RERA 2016 and the applicable Rent Act, with the CPC.",
        sections: [
            LitigatorSection(
                key: "prop-suits", title: "Property Suits", template: "plaint",
                draftInstruction: "Draft the property suit: title / declaration / partition / specific performance / possession / injunction — pleading the plaintiff's title, the cause of action, valuation and court fee, and the relief.",
                items: [
                    LitigatorItem(id: "prop-title", label: "Title / declaration suit"),
                    LitigatorItem(id: "prop-partition", label: "Partition suit"),
                    LitigatorItem(id: "prop-specific-performance", label: "Specific-performance suit"),
                    LitigatorItem(id: "prop-possession", label: "Possession / injunction suit"),
                ]),
            LitigatorSection(
                key: "rera", title: "RERA", template: "rera-compliance",
                draftInstruction: "Draft the RERA document: a complaint before the Authority / Adjudicating Officer or an appeal to the Appellate Tribunal — pleading the registered project, the agreement, the default and the relief (refund / interest / possession / compensation).",
                items: [
                    LitigatorItem(id: "rera-complaint", label: "RERA complaint"),
                    LitigatorItem(id: "rera-appeal", label: "RERA appeal"),
                ]),
            LitigatorSection(
                key: "tenancy", title: "Landlord & Tenant", template: "legal-notice",
                draftInstruction: "Draft the landlord-tenant document: a notice to quit / determination of lease under s.106 TP Act, or an eviction petition under the applicable Rent Act — pleading the tenancy, the ground and the relief.",
                items: [
                    LitigatorItem(id: "tenancy-notice", label: "Notice to quit (s.106 TP Act)"),
                    LitigatorItem(id: "tenancy-eviction", label: "Eviction petition"),
                ]),
        ]),
    "labour": LitigatorArea(
        label: "Labour & Employment",
        codeNote: "Apply the Industrial Disputes Act 1947 (and the new labour codes as notified), the POSH Act 2013, and the applicable wage / gratuity legislation.",
        sections: [
            LitigatorSection(
                key: "id-disputes", title: "Industrial Disputes", template: "",
                draftInstruction: "Draft the industrial-dispute document: a statement of claim before the Labour Court / Industrial Tribunal, or a s.33C(2) application for recovery of dues — pleading the workman status, the dispute and the relief.",
                items: [
                    LitigatorItem(id: "id-claim", label: "Statement of claim (Labour Court / Tribunal)"),
                    LitigatorItem(id: "id-33c2", label: "Recovery of dues (s.33C(2))"),
                ]),
            LitigatorSection(
                key: "posh", title: "POSH", template: "workplace-policy",
                draftInstruction: "Draft the POSH document: a complaint to the Internal Committee under the POSH Act 2013, the inquiry note, or an appeal under s.18 — maintaining confidentiality and the prescribed procedure.",
                items: [
                    LitigatorItem(id: "posh-complaint", label: "POSH complaint (to IC)"),
                    LitigatorItem(id: "posh-appeal", label: "POSH appeal (s.18)"),
                ]),
            LitigatorSection(
                key: "emp-claims", title: "Wages & Termination", template: "",
                draftInstruction: "Draft the employment claim / writ: a claim for wages / gratuity / bonus, or a writ challenging termination — pleading the entitlement, the breach and the relief.",
                items: [
                    LitigatorItem(id: "emp-wages", label: "Wages / gratuity / bonus claim"),
                    LitigatorItem(id: "emp-termination", label: "Writ / challenge to termination"),
                ]),
        ]),
    "cyber": LitigatorArea(
        label: "Cyber & Data Protection",
        codeNote: "Apply the Digital Personal Data Protection Act 2023, the Information Technology Act 2000 and the IT Rules 2021, with s.63 BSA for electronic evidence.",
        sections: [
            LitigatorSection(
                key: "dpdp", title: "Data Protection (DPDP)", template: "data-protection",
                draftInstruction: "Draft the DPDP document: a grievance to the Data Fiduciary / Consent Manager, a complaint to the Data Protection Board under the DPDP Act 2023, or a breach-notification — pleading the personal-data processing, the contravention and the relief.",
                items: [
                    LitigatorItem(id: "dpdp-grievance", label: "Grievance to Data Fiduciary"),
                    LitigatorItem(id: "dpdp-complaint", label: "Complaint to Data Protection Board"),
                    LitigatorItem(id: "dpdp-breach", label: "Breach notification"),
                ]),
            LitigatorSection(
                key: "itact", title: "IT Act & Intermediary", template: "",
                draftInstruction: "Draft the IT Act document: an intermediary notice / takedown request under s.79 and IT Rules 2021 (Rule 3(1)(d)), a s.66 / 43A grievance, or a certificate for electronic evidence (s.63 BSA / old s.65B).",
                items: [
                    LitigatorItem(id: "it-takedown", label: "Takedown / intermediary notice (Rule 3(1)(d))"),
                    LitigatorItem(id: "it-grievance", label: "Grievance (s.66 / 43A)"),
                    LitigatorItem(id: "it-65b", label: "Electronic-evidence certificate (s.63 BSA)"),
                ]),
        ]),
    "company": LitigatorArea(
        label: "Corporate & Company",
        codeNote: "Apply the Companies Act 2013 and the NCLT Rules; cite the exact section and the tribunal's practice.",
        sections: [
            LitigatorSection(
                key: "oppression", title: "Oppression & Mismanagement", template: "nclt-company-petition",
                draftInstruction: "Draft the NCLT company petition: oppression & mismanagement under ss.241–242, or a class action under s.245 — pleading the acts complained of, the qualifying threshold, and the reliefs.",
                items: [
                    LitigatorItem(id: "nclt-241", label: "Oppression & mismanagement (ss.241–242)"),
                    LitigatorItem(id: "nclt-245", label: "Class action (s.245)"),
                ]),
            LitigatorSection(
                key: "scheme", title: "Schemes & Capital", template: "nclt-company-petition",
                draftInstruction: "Draft the scheme / capital document: a scheme of arrangement (ss.230–232), reduction of capital (s.66), or compounding — with the requisite disclosures and the prayer.",
                items: [
                    LitigatorItem(id: "nclt-scheme", label: "Scheme of arrangement (ss.230–232)"),
                    LitigatorItem(id: "nclt-reduction", label: "Reduction of capital (s.66)"),
                ]),
            LitigatorSection(
                key: "co-restoration", title: "Restoration & Other", template: "nclt-company-petition",
                draftInstruction: "Draft the restoration / other NCLT application: restoration under s.252, or another company petition — pleading the ground and the relief.",
                items: [
                    LitigatorItem(id: "nclt-252", label: "Restoration of company (s.252)"),
                    LitigatorItem(id: "nclt-other", label: "Other company petition / application"),
                ]),
        ]),
    "international": LitigatorArea(
        label: "International Law",
        codeNote: "Apply Part II of the Arbitration and Conciliation Act 1996 (New York / Geneva Conventions) and ss.13 / 44A CPC for foreign judgments.",
        sections: [
            LitigatorSection(
                key: "enforcement", title: "Enforcement (Foreign Award / Judgment)", template: "arbitration-petition",
                draftInstruction: "Draft the enforcement document: enforcement of a foreign arbitral award (Part II, ss.44–49) or a foreign judgment (s.44A / s.13 CPC) — pleading reciprocity, finality and the absence of the statutory bars.",
                items: [
                    LitigatorItem(id: "intl-foreign-award", label: "Enforcement of foreign award (Part II)"),
                    LitigatorItem(id: "intl-foreign-judgment", label: "Enforcement of foreign judgment (s.44A CPC)"),
                ]),
            LitigatorSection(
                key: "crossborder", title: "Cross-Border Relief", template: "",
                draftInstruction: "Draft the cross-border document: an anti-suit / anti-enforcement injunction or a related application — pleading the forum, the agreement and the vexation / oppression.",
                items: [
                    LitigatorItem(id: "intl-anti-suit", label: "Anti-suit / anti-enforcement injunction"),
                ]),
        ]),
]

/// Each Civil and Criminal section's own fields and drafting instruction — `SECTION_FORMS`.
/// A section with no entry here uses `LITIGATOR_GENERIC_SECTION_FIELDS` and its own instruction.
let LITIGATOR_SECTION_FORMS: [String: LitigatorSectionForm] = [
    "initiating": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "parties", label: "Parties & description", type: .textarea, placeholder: "Names, addresses & status"),
            LitigatorFormField(key: "factsCauseOfAction", label: "Facts & cause of action", type: .textarea, placeholder: "Facts, dates, cause of action", big: true),
            LitigatorFormField(key: "jurisdictionLimitation", label: "Jurisdiction & limitation", type: .text, placeholder: "Jurisdiction basis & limitation"),
            LitigatorFormField(key: "reliefSought", label: "Relief / prayer", type: .textarea, placeholder: "Reliefs / orders sought"),
            LitigatorFormField(key: "valuationFee", label: "Valuation / court fee", type: .text, placeholder: "Suit value & court fee"),
        ],
        draftInstruction: "Draft in numbered paragraphs with a cause-title, a distinct jurisdiction paragraph, a pleaded cause of action and limitation averment, followed by a specific prayer and a verification/affidavit clause; for Art. 226/227 writs prefix a synopsis and list of dates, and for an execution petition set out the decree, its date and the mode of execution sought."),
    "reply": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "pleadingRepliedTo", label: "Pleading replied to", type: .text, placeholder: "Which pleading you're answering"),
            LitigatorFormField(key: "preliminaryObjections", label: "Preliminary objections", type: .textarea, placeholder: "Maintainability, limitation, jurisdiction…"),
            LitigatorFormField(key: "paraWiseReply", label: "Para-wise reply", type: .textarea, placeholder: "Admit / deny each paragraph", big: true),
            LitigatorFormField(key: "additionalPleas", label: "Additional pleas / counter-claim", type: .textarea, placeholder: "New pleas or counter-claim"),
            LitigatorFormField(key: "responseStance", label: "Response nature", type: .select, options: ["Deny in full", "Admit in part", "Confess & avoid", "Counter-claim / set-off"]),
        ],
        draftInstruction: "Open with the preliminary objections, then give a para-wise reply that tracks the opponent's paragraph numbering (expressly admitting, denying or putting to strict proof each averment), followed by additional pleas and any counter-claim/set-off, and close with a verification and supporting affidavit; do not raise a fresh prayer except where a counter-claim or set-off is pleaded."),
    "issues": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "plaintiffCase", label: "Plaintiff's averments", type: .textarea, placeholder: "What the plaint asserts"),
            LitigatorFormField(key: "defendantDefence", label: "Defendant's defence", type: .textarea, placeholder: "What the defence denies"),
            LitigatorFormField(key: "disputedPoints", label: "Disputed points of fact & law", type: .textarea, placeholder: "Points of fact & law disputed", big: true),
            LitigatorFormField(key: "admittedFacts", label: "Admitted / undisputed facts", type: .text, placeholder: "Facts admitted by both"),
            LitigatorFormField(key: "onusOfProof", label: "Onus of proof", type: .text, placeholder: "Who bears the burden"),
        ],
        draftInstruction: "Frame numbered issues under Order 14 CPC arising only from the material propositions of fact or law affirmed by one party and denied by the other; each issue must be a single, precise and answerable question, exclude admitted facts, separate issues of law from issues of fact, and indicate the party on whom the onus of proof rests."),
    "bail": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "firNumber", label: "FIR / case no.", type: .text, placeholder: "FIR no. & police station"),
            LitigatorFormField(key: "offenceSections", label: "Offence & sections", type: .text, placeholder: "Sections invoked"),
            LitigatorFormField(key: "custodyStatus", label: "Custody status", type: .select, placeholder: "Applicant's status", options: ["Apprehending arrest (not yet arrested)", "In police custody", "In judicial custody", "Released on interim/PR bond", "Custody not required (bailable)"]),
            LitigatorFormField(key: "arrestCustody", label: "Arrest date & custody", type: .text, placeholder: "Arrest date & days in custody"),
            LitigatorFormField(key: "antecedents", label: "Antecedents", type: .textarea, placeholder: "Prior cases, or first offender"),
            LitigatorFormField(key: "grounds", label: "Grounds for bail / objections", type: .textarea, placeholder: "Grounds for bail / objections", big: true),
        ],
        draftInstruction: "Draft with the court cause-title, FIR/case number, police station and offence sections, then numbered paragraphs covering custody status and grounds (or the prosecution's objections), closing with a specific prayer and a verification/affidavit clause. Cite the correct provision (BNSS 482 anticipatory, 480 before Magistrate, 483 Sessions/HC, or default bail under BNSS 187(3)) and address flight risk, tampering with evidence and influencing witnesses."),
    "evidence": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "party", label: "Party leading evidence", type: .select, placeholder: "Whose witness", options: ["Plaintiff", "Defendant", "Complainant", "Prosecution", "Accused / Defence"]),
            LitigatorFormField(key: "witnessParticulars", label: "Witness particulars", type: .text, placeholder: "Name, age, address"),
            LitigatorFormField(key: "witnessCapacity", label: "Witness capacity", type: .text, placeholder: "Eye-witness, IO, expert…"),
            LitigatorFormField(key: "documentsToProve", label: "Documents / exhibits to prove", type: .textarea, placeholder: "Documents & exhibit marks"),
            LitigatorFormField(key: "factsToDepose", label: "Facts to depose (chief)", type: .textarea, placeholder: "Facts to depose on oath", big: true),
        ],
        draftInstruction: "Draft as a numbered affidavit on oath by the named witness under Order 18 Rule 4 CPC (or s.145 NI Act for cheque complaints), stating the deponent's particulars, deposing facts in the first person within personal knowledge, tendering and identifying each document by its exhibit mark, and ending with a verification clause and attestation/oath."),
    "cross": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "witnessId", label: "Witness (PW/DW)", type: .text, placeholder: "e.g. PW1 — name"),
            LitigatorFormField(key: "chiefSummary", label: "Examination-in-chief summary", type: .textarea, placeholder: "What the witness said in chief", big: true),
            LitigatorFormField(key: "contradictionsOmissions", label: "Contradictions & omissions", type: .textarea, placeholder: "Contradictions & omissions"),
            LitigatorFormField(key: "confrontDocs", label: "Documents to confront with", type: .text, placeholder: "Prior statements / documents"),
            LitigatorFormField(key: "objective", label: "Objective of cross", type: .text, placeholder: "Aim of the cross"),
        ],
        draftInstruction: "Produce a numbered series of short, single-fact leading questions grouped by theme, moving from safe admissions to contradictions and omissions, expressly putting prior inconsistent statements and documents to the witness, and avoiding open-ended questions; close with the specific suggestions the witness is to be given (and expected to deny)."),
    "arguments": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "partyRepresented", label: "Party represented", type: .text, placeholder: "Party you represent"),
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "issuesToArgue", label: "Points / issues to argue", type: .textarea, placeholder: "Points / issues to argue", big: true),
            LitigatorFormField(key: "keyRecordRefs", label: "Facts & record references", type: .textarea, placeholder: "Facts with exhibit/page refs"),
            LitigatorFormField(key: "authorities", label: "Authorities to rely on", type: .textarea, placeholder: "Case law & provisions"),
            LitigatorFormField(key: "opponentContentions", label: "Opponent's contentions", type: .textarea, placeholder: "Opponent's points to rebut"),
        ],
        draftInstruction: "Draft issue-wise: state each point, then the party's submission with specific record references, then the supporting authorities with pin-cites, and where relevant distinguish the opponent's contentions. End with a concise conclusion and the precise relief prayed."),
    "applications": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "provisionInvoked", label: "Provision invoked", type: .text, placeholder: "e.g. Order 39 R1&2 CPC"),
            LitigatorFormField(key: "reliefSought", label: "Relief / prayer sought", type: .textarea, placeholder: "Exact orders prayed for"),
            LitigatorFormField(key: "grounds", label: "Grounds & supporting facts", type: .textarea, placeholder: "Facts & grounds for relief", big: true),
            LitigatorFormField(key: "urgency", label: "Urgency", type: .select, options: ["Urgent — mention/same day", "Urgent — early hearing", "Ordinary course"]),
            LitigatorFormField(key: "orderOrAppReplied", label: "Order / application concerned", type: .text, placeholder: "Order/application concerned"),
        ],
        draftInstruction: "Draft with cause title, the enabling provision in the heading, numbered grounds narrating the facts, and a distinct prayer paragraph seeking the precise relief; note that it is supported by an affidavit, and for interim/urgent matters include the specific interim prayer pending disposal."),
    "post-trial": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "impugnedOrder", label: "Impugned judgment / order", type: .text, placeholder: "Court, case no. & date"),
            LitigatorFormField(key: "convictionSentence", label: "Sentence / order impugned", type: .textarea, placeholder: "Sentence or order impugned"),
            LitigatorFormField(key: "enablingProvision", label: "Enabling provision", type: .select, options: ["Appeal against conviction (BNSS 415)", "Appeal against acquittal / victim (BNSS 413)", "Revision (BNSS 438)", "Suspension of sentence & bail (BNSS 430)", "Quashing (BNSS 528)", "Plea bargaining (BNSS Ch. XXIII)", "Probation / sentence mitigation"]),
            LitigatorFormField(key: "groundsOfChallenge", label: "Grounds of challenge", type: .textarea, placeholder: "Grounds of challenge", big: true),
            LitigatorFormField(key: "reliefSought", label: "Relief sought", type: .text, placeholder: "Relief sought on appeal"),
            LitigatorFormField(key: "limitationDelay", label: "Limitation / delay", type: .text, placeholder: "Within limitation, or delay"),
        ],
        draftInstruction: "Draft as a memorandum of appeal/revision/petition with cause-title, particulars of the impugned judgment (court, case number, date, sentence) and limitation position, followed by grounds set out as separately numbered paragraphs, and close with a specific prayer citing the enabling BNSS provision. Where delay exists, include a condonation-of-delay paragraph."),
    "common": LitigatorSectionForm(
        inputs: [
            LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
            LitigatorFormField(key: "parties", label: "Parties", type: .text, placeholder: "Applicant v. respondent"),
            LitigatorFormField(key: "deponentExecutant", label: "Deponent / executant", type: .text, placeholder: "Signatory's name & details"),
            LitigatorFormField(key: "caseReference", label: "Case / notice reference", type: .text, placeholder: "Case or cheque reference"),
            LitigatorFormField(key: "particulars", label: "Key particulars", type: .text, placeholder: "Amount, bond, or copies"),
            LitigatorFormField(key: "detailsNarrative", label: "Facts / details", type: .textarea, placeholder: "Facts / instructions needed", big: true),
        ],
        draftInstruction: "Produce the exact standard format for the selected document with correct heading, full party array, operative clause and verification/attestation block. For an NI s.138 notice state the cheque particulars, dishonour and the mandatory 15-day demand; for affidavits use a numbered deponent verification clause; for vakalatnama/surety documents include the authority and undertaking clauses."),
]

/// The fields a section without a form of its own is given — `GENERIC_SECTION_FIELDS`.
let LITIGATOR_GENERIC_SECTION_FIELDS: [LitigatorFormField] = [
    LitigatorFormField(key: "forum", label: "Court / forum", type: .forum),
    LitigatorFormField(key: "parties", label: "Parties", type: .text, placeholder: "Parties & their status"),
    LitigatorFormField(key: "facts", label: "Facts & background", type: .textarea, placeholder: "Facts, dates, cause of action", big: true),
    LitigatorFormField(key: "relief", label: "Relief / prayer sought", type: .textarea, placeholder: "Reliefs / orders sought"),
]
