// Generated from the platform's own card modules — do not edit by hand.
//
// Produced by evaluating src/roles/*Cards.js and src/tools/registry.js under Node, the
// same way the twenty-nine tool prompts were pinned. If a card changes on the platform,
// regenerate this file and its fixtures rather than editing either to match: the
// fixture is the contract and this is the copy.

import Foundation

let ROLE_CARDS: [RoleCard] = [
    RoleCard(
        id: "legal-opinion", role: .seniorCounsel,
        title: "Legal Opinion",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Formal written opinion", "Short advice / note", "Second opinion", "Opinion on a specific question", "Opinion on title / documents"],
        note: "Write a formal legal opinion in counsel's register, structured as: Questions presented; Assumed facts & documents relied on; issue-wise Analysis citing authorities with their good-law status; a clear Opinion; and Assumptions, caveats & further material required. Do not overstate — where the law is unsettled, say so."
    ),
    RoleCard(
        id: "argument-note", role: .seniorCounsel,
        title: "Complete Argument Note",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Full argument note (all issues)", "Issue-wise argument note", "Opening submissions", "Written submissions (final)", "Oral argument — talking points", "Reply / rejoinder arguments", "Note on a single issue"],
        note: "Prepare a complete, court-ready argument note. Open with a short synopsis and the questions that arise, then argue ISSUE BY ISSUE — for each issue set out: the proposition (of law or fact); the submission with its reasoning; the authorities relied on (pin-cited, each tagged with its good-law status); the references to the record (page / paragraph / exhibit); and the opponent's likely answer with the rebuttal to it. Close with the relief / prayer. Written in the register of arguing counsel — forceful yet measured, never overstating; where the law is unsettled, say so, and never fabricate a citation."
    ),
    RoleCard(
        id: "conference-note", role: .seniorCounsel,
        title: "Conference Note / Advice on Brief",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Advice on brief", "Conference note", "Note to instructing advocate / AOR", "Advice on next steps", "Advice on further evidence to gather"],
        note: "Prepare counsel's note after a conference: a candid view on the merits, the gaps in the evidence, the next steps, and precisely what to obtain from the client / instructing advocate (AOR) before the next stage."
    ),
    RoleCard(
        id: "merits-strategy", role: .seniorCounsel,
        title: "Merits & Strategy Note",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Merits assessment", "Forum & strategy", "Interim-relief strategy", "Cost-benefit & risk", "Settlement leverage"],
        note: "Give a candid, senior assessment: realistic prospects, the correct forum, the reliefs and their likelihood, limitation, the interim strategy (prima facie case / balance of convenience / irreparable injury), the key risks, and any settlement leverage. Be honest about the weaknesses."
    ),
    RoleCard(
        id: "advice-evidence", role: .seniorCounsel,
        title: "Advice on Evidence",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["What evidence to lead", "Admissibility analysis (BSA)", "Burden & onus of proof", "Documentary vs oral evidence", "Witness plan", "Gaps in the evidence"],
        note: "Advise on evidence under the Bharatiya Sakshya Adhiniyam, 2023 (BSA): what to lead and how, admissibility and its conditions, who bears the burden and onus on each issue, the documentary/oral mix, the witness plan, and the gaps to plug before trial."
    ),
    RoleCard(
        id: "maintainability", role: .seniorCounsel,
        title: "Note on Maintainability",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Maintainability opinion", "Preliminary objections", "Limitation note", "Locus standi", "Alternative-remedy bar", "Res judicata"],
        note: "Analyse the threshold objections precisely: jurisdiction, limitation, locus standi, the availability of an alternative statutory remedy, res judicata / constructive res judicata, and any statutory bar — citing the governing provision and authority with its good-law status."
    ),
    RoleCard(
        id: "devils-advocate", role: .seniorCounsel,
        title: "Devil's Advocate",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Opponent's best case", "Anticipated rebuttals", "Weakness audit of my case", "Likely questions from the Bench"],
        note: "Argue the other side at its strongest, then show how to meet it: set out the opponent's best case, the rebuttals they will raise, the weaknesses in our own case, and the questions the Bench is likely to ask — so counsel can pre-empt each."
    ),
    RoleCard(
        id: "question-of-law", role: .seniorCounsel,
        title: "Substantial Question of Law",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Frame the substantial question (second appeal, s.100 CPC)", "Grounds for SLP (Art. 136)", "Questions for review / curative", "Question for reference to a larger bench"],
        note: "Frame the precise question(s) of law the appeal turns on — for a second appeal, a substantial question under Section 100 CPC; for a Special Leave Petition, the questions warranting interference under Article 136 — each stated as a single, answerable proposition with the supporting authority."
    ),
    RoleCard(
        id: "compilation-authorities", role: .seniorCounsel,
        title: "Compilation of Authorities",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: [],
        dropdown: ["Compilation of authorities", "Convenience compilation", "Case digest with good-law status", "Statute / provision compilation"],
        note: "Assemble the authorities counsel will rely on: full citations, the proposition each supports (pin-cited), and each authority's current standing [Settled] / [Doubted] / [Overruled] / [Pending]. Arrange them in the order they will be argued."
    ),
    RoleCard(
        id: "case-summary", role: .adjudicator,
        title: "Case File & Record Summary",
        subtitle: nil,
        section: "Case File & Record",
        output: .document,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Pleadings summary", "Chronology / list of dates", "Parties & reliefs claimed", "Issues / points for determination (extract, not decide)", "Document index digest"],
        note: "Extract and organise only — do NOT decide, weigh, or opine on any issue. Points for determination are to be EXTRACTED as framed, not resolved."
    ),
    RoleCard(
        id: "submissions-digest", role: .adjudicator,
        title: "Neutral Submissions Digest",
        subtitle: nil,
        section: "Case File & Record",
        output: .document,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Party-wise contentions (side-by-side)", "Rival-contentions table", "Prayer / relief comparison", "Common-ground vs disputed-issues map"],
        note: "Organise and present each side's submissions neutrally, side by side. Do NOT weigh them, prefer one, or recommend a finding."
    ),
    RoleCard(
        id: "evidence-analysis", role: .adjudicator,
        title: "Evidence & Deposition Analysis",
        subtitle: nil,
        section: "Evidence & Analysis",
        output: .research,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Witness-wise deposition summary", "Contradiction / inconsistency finder", "Exhibit / documentary-evidence digest", "Evidence-to-issue mapping (neutral)", "Cross-examination highlights"],
        note: "Neutral, mechanical analysis only. Map evidence to issues and surface contradictions WITHOUT assessing credibility, weighing evidence, or recommending a finding."
    ),
    RoleCard(
        id: "legal-research", role: .adjudicator,
        title: "Legal Research & Citation Check",
        subtitle: nil,
        section: "Research & Language",
        output: .research,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Precedent search", "Statutory provision & current status", "\"Is it still good law?\" verification", "Digest of authorities cited by parties", "Distinguish / follow analysis (research only)"],
        note: "Research aid only. Give precedents and statutory status with real, verifiable citations; verify whether each authority is still good law. Do NOT apply the law to decide this case."
    ),
    RoleCard(
        id: "translation", role: .adjudicator,
        title: "Language & Translation",
        subtitle: nil,
        section: "Research & Language",
        output: .document,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Judgment / order translation (EN ↔ regional)", "Document translation", "Regional-language deposition summary", "Multilingual case-file navigation"],
        note: "Translate faithfully and preserve legal meaning, party names, dates and citations. Do not summarise away substance unless a summary is expressly requested."
    ),
    RoleCard(
        id: "hearing-mgmt", role: .adjudicator,
        title: "Hearing & Cause-List Management",
        subtitle: nil,
        section: "Hearing & Administration",
        output: .document,
        isSafetyFirst: false,
        filters: ["judge", "arbitrator"],
        dropdown: ["Cause-list note", "Hearing schedule", "Procedural timetable", "Time-bound directions tracker", "Adjournment log"],
        note: "Administrative / scheduling output only. Organise dates, directions and logs; take no view on the merits."
    ),
    RoleCard(
        id: "award-drafting", role: .adjudicator,
        title: "Award Drafting",
        subtitle: "Assistive scaffold — arbitrator supplies the findings",
        section: "Award & Adjudicatory Drafting",
        output: .document,
        isSafetyFirst: false,
        filters: ["arbitrator"],
        dropdown: ["Recitals / procedural history", "Parties & background", "Issues for determination", "Submissions summary", "Reasoning scaffold", "Operative award", "Interim award", "Jurisdiction award (Sec. 16)", "Scott schedule (construction claims)", "Interest", "Signature / dissent block"],
        note: "Assemble an ARBITRAL AWARD SCAFFOLD under the Arbitration and Conciliation Act, 1996. The arbitrator supplies the findings and reasoning: in the reasoning section insert clear \"[Arbitrator to record findings and reasons]\" placeholders rather than deciding anything yourself. The arbitrator applies their own mind; the tool only assembles and formats."
    ),
    RoleCard(
        id: "procedural-orders", role: .adjudicator,
        title: "Procedural Orders & Reference Management",
        subtitle: nil,
        section: "Award & Adjudicatory Drafting",
        output: .document,
        isSafetyFirst: false,
        filters: ["arbitrator"],
        dropdown: ["First Procedural Order (PO1)", "Terms of Reference", "Directions order", "Document-production order (Redfern Schedule)", "Sec. 17 interim-measure order", "Sec. 16 jurisdiction ruling", "Emergency-arbitrator order", "Sec. 29A timeline tracker", "Sec. 29A extension application", "Institutional-rule PO (SIAC / ICC / MCIA / DIAC)", "Consent / settlement award (Sec. 30)"],
        note: "Draft the procedural order / reference document under the Arbitration and Conciliation Act, 1996 (ss. 16, 17, 29A, 30 as applicable)."
    ),
    RoleCard(
        id: "costs-interest", role: .adjudicator,
        title: "Costs & Interest",
        subtitle: nil,
        section: "Costs & Interest",
        output: .document,
        isSafetyFirst: false,
        filters: ["arbitrator"],
        dropdown: ["Costs determination (Sec. 31A)", "Quantum reasoning", "Cost allocation", "Pre / post-award interest computation"],
        note: "Apply ss. 31 and 31A of the Arbitration and Conciliation Act, 1996 for costs and interest. Show the computation; leave rate / quantum inputs as [placeholders] where the arbitrator must decide."
    ),
    RoleCard(
        id: "precedent-pull", role: .adjudicator,
        title: "Precedent Pull & Good-Law Check",
        subtitle: nil,
        section: "Judge-Only Tools",
        output: .research,
        isSafetyFirst: false,
        filters: ["judge"],
        dropdown: ["Deep precedent search", "Citator (overruled / affirmed / distinguished)", "Provision-wise authority map", "Headnote of an existing judgment"],
        note: "Research aid ONLY — do not draft any part of the ruling. Provide precedents, citator status (overruled / affirmed / distinguished) and authority maps with real citations."
    ),
    RoleCard(
        id: "judgment-formatting", role: .adjudicator,
        title: "Judgment Formatting Aid",
        subtitle: "Structure only — works on the judge's own draft",
        section: "Judge-Only Tools",
        output: .document,
        isSafetyFirst: false,
        filters: ["judge"],
        dropdown: ["Cause-title / preamble formatting", "Heading & paragraph scaffolding", "Citation formatting & neutral-citation check", "Consistency / typo check on the judge's own draft"],
        note: "Work ONLY on the text the judge has already authored (pasted below). Format, structure and check consistency / citations. Do NOT generate reasoning, findings, sentencing, or any operative part, and do NOT add new legal content."
    ),
    RoleCard(
        id: "commercial-agreements", role: .corporateCounsel,
        title: "Commercial Agreements",
        subtitle: nil,
        section: "Drafting — Commercial & General",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "TMT"],
        dropdown: ["NDA / mutual NDA", "MSA", "Service / consultancy", "SOW / SLA", "Vendor / supply / procurement", "Distribution / reseller", "Agency", "Franchise", "Licensing (general)", "MoU / LOI"],
        note: ""
    ),
    RoleCard(
        id: "sale-supply-goods", role: .corporateCounsel,
        title: "Sale & Supply of Goods",
        subtitle: nil,
        section: "Drafting — Commercial & General",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "PROJ", "AVI", "SHIP", "LIFE"],
        dropdown: ["Sale of goods", "Purchase order terms", "Supply agreement", "Manufacturing / OEM", "Toll-manufacturing"],
        note: ""
    ),
    RoleCard(
        id: "entity-formation", role: .corporateCounsel,
        title: "Entity Formation & Structuring",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["CORP", "GEN", "PVT"],
        dropdown: ["MoA", "AoA", "LLP agreement", "Partnership deed", "Incorporation set (SPICe+)", "Founders'/promoters' agreement", "Branch / LO / subsidiary setup"],
        note: ""
    ),
    RoleCard(
        id: "ma-transaction", role: .corporateCounsel,
        title: "M&A Transaction Documents",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["CORP", "PE", "CAPM"],
        dropdown: ["Term sheet / LOI", "SPA", "SSA", "Business transfer (slump sale)", "Asset purchase", "Warranty & indemnity", "Disclosure schedules", "Scheme of arrangement (Sec. 230–232)"],
        note: ""
    ),
    RoleCard(
        id: "investment-pevc", role: .corporateCounsel,
        title: "Investment / PE-VC Documents",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["PE", "CORP", "FIN"],
        dropdown: ["Term sheet", "SSA", "SHA", "Convertibles (CCPS / CCD / SAFE)", "Side letter", "ESOP pool", "Cap table", "Founders' vesting"],
        note: ""
    ),
    RoleCard(
        id: "jv-shareholder", role: .corporateCounsel,
        title: "Joint Venture & Shareholder Arrangements",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["CORP", "PROJ", "PE"],
        dropdown: ["JV agreement", "SHA", "Voting agreement", "Deadlock / exit mechanics", "Promoter agreement"],
        note: ""
    ),
    RoleCard(
        id: "finance-lending", role: .corporateCounsel,
        title: "Finance & Lending Documents",
        subtitle: nil,
        section: "Drafting — Banking, Finance & Capital Markets",
        output: .document,
        isSafetyFirst: false,
        filters: ["BANK", "CORP", "PE"],
        dropdown: ["Facility / loan agreement", "Sanction letter", "Debentures / bonds", "Guarantee", "Security (mortgage / pledge / hypothecation)", "Inter-creditor", "Subordination"],
        note: ""
    ),
    RoleCard(
        id: "capital-markets", role: .corporateCounsel,
        title: "Capital Markets Documents",
        subtitle: nil,
        section: "Drafting — Banking, Finance & Capital Markets",
        output: .document,
        isSafetyFirst: false,
        filters: ["CAPM", "BANK", "CORP"],
        dropdown: ["DRHP / prospectus", "Private placement (PAS-4)", "Underwriting", "Placement memorandum", "InvIT / REIT", "Buyback / rights issue docs"],
        note: ""
    ),
    RoleCard(
        id: "restructuring-ibc", role: .corporateCounsel,
        title: "Restructuring & Insolvency (IBC)",
        subtitle: nil,
        section: "Drafting — Banking, Finance & Capital Markets",
        output: .document,
        isSafetyFirst: false,
        filters: ["RI", "BANK"],
        dropdown: ["Sec. 8 demand notice", "Sec. 7 / 9 / 10 application", "Resolution plan", "CoC documents", "One-time settlement", "Restructuring / standstill agreement"],
        note: ""
    ),
    RoleCard(
        id: "employment-hr", role: .corporateCounsel,
        title: "Employment & HR",
        subtitle: nil,
        section: "Drafting — Employment & Labour",
        output: .document,
        isSafetyFirst: false,
        filters: ["EMP", "GEN"],
        dropdown: ["Offer letter", "Employment agreement", "Consultant / contractor", "Non-compete / non-solicit", "Secondment", "Separation / settlement / release"],
        note: ""
    ),
    RoleCard(
        id: "esop-incentives", role: .corporateCounsel,
        title: "ESOP & Incentives",
        subtitle: nil,
        section: "Drafting — Employment & Labour",
        output: .document,
        isSafetyFirst: false,
        filters: ["EMP", "PE", "CORP"],
        dropdown: ["ESOP scheme", "Grant letter", "SAR", "Phantom stock", "Trust deed (ESOP trust)"],
        note: ""
    ),
    RoleCard(
        id: "workplace-policies", role: .corporateCounsel,
        title: "Workplace Policies",
        subtitle: nil,
        section: "Drafting — Employment & Labour",
        output: .document,
        isSafetyFirst: false,
        filters: ["EMP", "GEN"],
        dropdown: ["POSH policy (Act 2013)", "Code of conduct", "HR handbook", "Whistleblower", "WFH / moonlighting", "DEI"],
        note: ""
    ),
    RoleCard(
        id: "ip-agreements", role: .corporateCounsel,
        title: "IP Agreements",
        subtitle: nil,
        section: "Drafting — IP & Technology",
        output: .document,
        isSafetyFirst: false,
        filters: ["IP", "TMT", "LIFE"],
        dropdown: ["IP assignment", "Trademark / patent / copyright licence", "Technology transfer", "Coexistence", "IP-heavy franchise"],
        note: ""
    ),
    RoleCard(
        id: "ip-prosecution", role: .corporateCounsel,
        title: "IP Prosecution & Filings (PATMA)",
        subtitle: nil,
        section: "Drafting — IP & Technology",
        output: .document,
        isSafetyFirst: false,
        filters: ["IP"],
        dropdown: ["Trademark application", "Reply to examination report", "Patent application / specification", "Copyright registration", "Design registration", "Opposition / rectification"],
        note: ""
    ),
    RoleCard(
        id: "tech-data-agreements", role: .corporateCounsel,
        title: "Technology & Data Agreements",
        subtitle: nil,
        section: "Drafting — IP & Technology",
        output: .document,
        isSafetyFirst: false,
        filters: ["TMT", "DATA", "FIN"],
        dropdown: ["SaaS / software licence", "EULA", "Cloud / hosting", "API terms", "Website T&C", "Reseller (tech)"],
        note: ""
    ),
    RoleCard(
        id: "data-protection", role: .corporateCounsel,
        title: "Data Protection Pack",
        subtitle: nil,
        section: "Drafting — Data Protection & Privacy",
        output: .document,
        isSafetyFirst: false,
        filters: ["DATA", "TMT", "FIN", "LIFE"],
        dropdown: ["Privacy policy", "Consent notice", "DPA / processing addendum", "DPIA", "Cross-border transfer", "Breach notification", "DPDP compliance note"],
        note: ""
    ),
    RoleCard(
        id: "real-estate", role: .corporateCounsel,
        title: "Real Estate Documents",
        subtitle: nil,
        section: "Drafting — Real Estate, Construction & Infrastructure",
        output: .document,
        isSafetyFirst: false,
        filters: ["RE", "GEN"],
        dropdown: ["Sale / conveyance deed", "Lease deed", "Leave & licence", "Agreement to sell", "Development / JDA", "TDR", "Mortgage deed"],
        note: ""
    ),
    RoleCard(
        id: "construction-infra", role: .corporateCounsel,
        title: "Construction & Infra Contracts",
        subtitle: nil,
        section: "Drafting — Real Estate, Construction & Infrastructure",
        output: .document,
        isSafetyFirst: false,
        filters: ["RE", "PROJ"],
        dropdown: ["EPC contract", "Works contract", "FIDIC-style", "O&M", "Concession / PPP", "Consultancy (design)"],
        note: ""
    ),
    RoleCard(
        id: "rera-compliance", role: .corporateCounsel,
        title: "RERA & Property Compliance",
        subtitle: nil,
        section: "Drafting — Real Estate, Construction & Infrastructure",
        output: .document,
        isSafetyFirst: false,
        filters: ["RE"],
        dropdown: ["RERA registration", "Mandatory disclosures", "Allotment letter", "Builder-buyer agreement"],
        note: ""
    ),
    RoleCard(
        id: "projects-energy", role: .corporateCounsel,
        title: "Projects & Energy Documents",
        subtitle: nil,
        section: "Drafting — Real Estate, Construction & Infrastructure",
        output: .document,
        isSafetyFirst: false,
        filters: ["PROJ", "RE", "BANK"],
        dropdown: ["Power purchase agreement (PPA)", "Concession", "Fuel / gas supply", "Implementation agreement", "Land aggregation", "O&M", "Wheeling / open-access"],
        note: ""
    ),
    RoleCard(
        id: "aviation-defence", role: .corporateCounsel,
        title: "Aviation & Defence",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["AVI"],
        dropdown: ["Aircraft lease (dry / wet / ACMI)", "Aircraft purchase", "MRO", "GSA", "Defence procurement / offset", "Slot / ground-handling"],
        note: ""
    ),
    RoleCard(
        id: "shipping-maritime", role: .corporateCounsel,
        title: "Shipping & Maritime",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["SHIP", "INS"],
        dropdown: ["Charterparty (time / voyage / bareboat)", "Bill of lading", "Ship sale / purchase (MOA)", "Bunker supply", "Ship management", "Marine insurance"],
        note: ""
    ),
    RoleCard(
        id: "life-sciences", role: .corporateCounsel,
        title: "Life Sciences & Healthcare",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["LIFE", "IP"],
        dropdown: ["Clinical trial agreement", "CRO / CMO", "In-licensing / out-licensing", "Hospital MSA", "Distribution", "Regulatory (CDSCO) filings"],
        note: ""
    ),
    RoleCard(
        id: "insurance", role: .corporateCounsel,
        title: "Insurance Documents",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["INS", "BANK"],
        dropdown: ["Policy wording", "Reinsurance", "Bancassurance", "Broker / agency", "Claims / subrogation"],
        note: ""
    ),
    RoleCard(
        id: "fintech-reg", role: .corporateCounsel,
        title: "Fintech & Financial-Services Regulatory",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["FIN", "BANK", "DATA"],
        dropdown: ["Co-lending / DLG", "Digital-lending agreement", "PA / PG agreement", "Sourcing / BC", "Account Aggregator", "BBPS", "RBI / SEBI reg. note"],
        note: ""
    ),
    RoleCard(
        id: "media-entertainment", role: .corporateCounsel,
        title: "Media & Entertainment (TMT)",
        subtitle: nil,
        section: "Drafting — Sector-Specific Commercial",
        output: .document,
        isSafetyFirst: false,
        filters: ["TMT", "IP"],
        dropdown: ["Content licensing", "Production", "Talent / artist", "Publishing", "OTT distribution", "Advertising / influencer"],
        note: ""
    ),
    RoleCard(
        id: "board-secretarial", role: .corporateCounsel,
        title: "Board & Secretarial",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["CORP", "GEN", "CAPM"],
        dropdown: ["Board resolution", "Shareholder resolution", "Meeting notice + agenda", "Minutes (Board / AGM / EGM)", "Statutory registers", "MCA / ROC filings", "RPT approval (Sec. 188)", "Directors' report"],
        note: ""
    ),
    RoleCard(
        id: "listed-compliance", role: .corporateCounsel,
        title: "Listed Company Compliance",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["CAPM", "CORP"],
        dropdown: ["SEBI LODR disclosures", "PIT / insider-trading code", "Corporate governance report", "Committee charters", "Open offer / SAST"],
        note: ""
    ),
    RoleCard(
        id: "legal-opinions", role: .corporateCounsel,
        title: "Legal Opinions & Memos",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "TAX", "BANK"],
        dropdown: ["Legal opinion", "Memo of advice", "Position paper", "Board / management note", "Risk memo"],
        note: ""
    ),
    RoleCard(
        id: "regulatory-advisory", role: .corporateCounsel,
        title: "Regulatory Advisory & Applications",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["FIN", "BANK", "INS", "LIFE", "AVI", "TMT", "DATA"],
        dropdown: ["Licence / registration application", "Response to show-cause", "Regulator representation", "Sector approval note"],
        note: ""
    ),
    RoleCard(
        id: "compliance-calendar", role: .corporateCounsel,
        title: "Corporate Calendar",
        subtitle: "Companies Act · SEBI · FEMA · Labour · Tax · sector",
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN"],
        dropdown: [],
        note: ""
    ),
    RoleCard(
        id: "fema-fdi", role: .corporateCounsel,
        title: "FEMA / FDI & Cross-Border",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["CORP", "BANK", "PE"],
        dropdown: ["FC-GPR", "FC-TRS", "ODI", "ECB filings", "FDI sectoral-cap note", "Downstream investment"],
        note: ""
    ),
    RoleCard(
        id: "antitrust", role: .corporateCounsel,
        title: "Antitrust / Competition",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["ANTI", "CORP"],
        dropdown: ["CCI notification (Form I / II)", "Gun-jumping analysis", "Merger-control note", "Leniency application", "Competition compliance policy"],
        note: ""
    ),
    RoleCard(
        id: "trade-wto", role: .corporateCounsel,
        title: "Trade, WTO & Customs",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["WTO", "SHIP", "AVI"],
        dropdown: ["Anti-dumping / safeguard", "Customs classification / valuation", "FTP / DGFT", "Trade-remedy submission", "Export-control note"],
        note: ""
    ),
    RoleCard(
        id: "tax-documents", role: .corporateCounsel,
        title: "Tax Documents",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["TAX", "CORP", "WTO"],
        dropdown: ["Tax opinion", "GST advisory", "Transfer pricing (study / agreement)", "DTAA analysis", "Structuring note", "Advance ruling application", "Reply to tax notice"],
        note: ""
    ),
    RoleCard(
        id: "private-client", role: .corporateCounsel,
        title: "Private Client & Estate",
        subtitle: nil,
        section: "Private Client",
        output: .document,
        isSafetyFirst: false,
        filters: ["PVT", "RE", "TAX"],
        dropdown: ["Will", "Trust deed", "Gift deed", "Family settlement", "Succession / probate note", "Power of attorney", "Family constitution"],
        note: ""
    ),
    RoleCard(
        id: "notices-predispute", role: .corporateCounsel,
        title: "Notices & Pre-Dispute",
        subtitle: nil,
        section: "Disputes",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN"],
        dropdown: ["Legal / demand notice", "Breach / termination", "Recovery notice (incl. NI s.138)", "Cease & desist", "Reply to notice"],
        note: ""
    ),
    RoleCard(
        id: "arbitration-docs", role: .corporateCounsel,
        title: "Arbitration Documents",
        subtitle: nil,
        section: "Disputes",
        output: .document,
        isSafetyFirst: false,
        filters: ["ARB", "CORP", "PROJ", "RE"],
        dropdown: ["Arbitration clause / agreement", "Notice of arbitration (invocation)", "Terms of reference", "Statement of claim / defence", "Settlement / consent award"],
        note: ""
    ),
    RoleCard(
        id: "white-collar", role: .corporateCounsel,
        title: "White-Collar / Internal Investigations",
        subtitle: nil,
        section: "Disputes",
        output: .document,
        isSafetyFirst: false,
        filters: ["WCC", "BANK", "GEN"],
        dropdown: ["Internal investigation report", "Whistleblower-complaint handling", "Anti-bribery / FCPA / PCA policy", "Compliance advisory", "Suspicious-transaction note"],
        note: ""
    ),
    RoleCard(
        id: "corporate-litigation", role: .corporateCounsel,
        title: "Litigation & Court Filings",
        subtitle: "Corporate-drafted court documents",
        section: "Disputes",
        output: .document,
        isSafetyFirst: false,
        filters: ["LIT", "CORP", "GEN"],
        dropdown: ["Plaint / civil suit", "Written statement", "Interim application (injunction / stay)", "Reply / rejoinder", "Execution petition", "Memorandum of appeal", "Company petition (NCLT)", "Writ petition", "Caveat"],
        note: ""
    ),
    RoleCard(
        id: "termsheet-negotiation", role: .corporateCounsel,
        title: "Term Sheet & Negotiation",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "PE"],
        dropdown: ["Term sheet / LOI", "Term-sheet redline & mark-up", "Issues list / negotiation matrix", "Fall-back positions note"],
        note: ""
    ),
    RoleCard(
        id: "disclosure-letter", role: .corporateCounsel,
        title: "Disclosure Letter & Schedules",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP"],
        dropdown: ["Disclosure letter", "General disclosures", "Specific disclosures", "Disclosure schedules", "Bring-down disclosure"],
        note: ""
    ),
    RoleCard(
        id: "deal-execution", role: .corporateCounsel,
        title: "Deal Execution & Closing",
        subtitle: nil,
        section: "Drafting — Corporate, M&A & Investment",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "PE"],
        dropdown: ["CP checklist", "CP-satisfaction certificate", "Closing agenda & mechanics", "Conditions-subsequent tracker", "Completion / closing memorandum", "Escrow instructions"],
        note: ""
    ),
    RoleCard(
        id: "related-party", role: .corporateCounsel,
        title: "Related-Party Framework",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "CAPM"],
        dropdown: ["RPT policy (Sec. 188)", "RPT approval note", "Audit-committee approval", "Arm's-length justification", "RPT register"],
        note: ""
    ),
    RoleCard(
        id: "esg-brsr", role: .corporateCounsel,
        title: "ESG & BRSR",
        subtitle: nil,
        section: "Advisory, Governance & Compliance",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "CORP", "CAPM"],
        dropdown: ["BRSR report support", "ESG policy", "ESG due-diligence note", "Sustainability disclosures"],
        note: ""
    ),
    RoleCard(
        id: "data-breach-runbook", role: .corporateCounsel,
        title: "Data-Breach Runbook",
        subtitle: nil,
        section: "Drafting — Data Protection & Privacy",
        output: .document,
        isSafetyFirst: false,
        filters: ["GEN", "DATA", "TMT"],
        dropdown: ["Breach-response runbook", "Breach notification (DPDP)", "Incident-assessment note", "Regulator / Board communication", "Post-incident review"],
        note: ""
    ),
    RoleCard(
        id: "learn-understand", role: .student,
        title: "Learn & Understand",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["law-student", "moot", "research"],
        dropdown: ["Explain a concept (with examples)", "Break down a doctrine", "Compare related concepts", "Statute / bare-act explainer", "\"Explain like I'm new to law\"", "Flowchart a legal process"],
        note: "Teach the concept with plain-language explanations, worked examples and analogies. End by checking understanding and inviting the student to attempt."
    ),
    RoleCard(
        id: "case-law-study", role: .student,
        title: "Case Law Study",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["law-student", "moot", "research"],
        dropdown: ["Case brief (facts–issue–held–ratio)", "Explain the ratio / obiter", "Landmark-case explainer", "Case comparison / line of authority", "\"Is this still good law?\" (with caveats)"],
        note: "Explain the case in student-friendly terms; clearly separate ratio from obiter and give the citation. Add lawyer-style caveats for good-law questions."
    ),
    RoleCard(
        id: "shepardize", role: .student,
        title: "Shepardizing the Law",
        subtitle: nil,
        section: nil,
        output: .research,
        isSafetyFirst: false,
        filters: ["law-student", "moot", "research"],
        dropdown: ["What is Shepardizing? (the citator method, explained)", "Is this case still good law? (treatment check)", "Trace subsequent treatment (followed / distinguished / doubted / overruled)", "Case history — affirmed, reversed or remanded on appeal", "Negative-treatment & red-flag check", "Build a citation-treatment table (signals & pin-cites)", "Verify a citation (case name, reporter, neutral & parallel cites)", "Binding vs persuasive — whom does this authority bind?", "Find the current leading authority on this point", "How to Shepardize in India (SCC Online / Manupatra walkthrough)"],
        note: "Teach and apply Shepardizing — the citator method of checking whether a judgment is still GOOD LAW by tracing how later courts have treated it. Explain the treatment signals (followed, affirmed, distinguished, explained, doubted, criticised, overruled, reversed, superseded by statute) and what each does to the authority's weight (binding vs persuasive). CRITICAL — never invent a citing case, citation or treatment: cite only authorities you can identify with confidence, tag each with a good-law status [Settled / Followed / Doubted / Distinguished / Overruled / Reversed / Pending], and where you cannot verify a point, say so plainly instead of guessing. Show the student how to CONFIRM status in India using citators (SCC Online, Manupatra, LiveLaw, Indian Kanoon) and the case's own appellate history. Teach the method and how to verify — do not just hand over a conclusion."
    ),
    RoleCard(
        id: "study-exam", role: .student,
        title: "Study & Exam Prep",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["law-student"],
        dropdown: ["Topic summary / revision notes", "Flashcards / Q&A", "Practice questions & model answers", "Issue-spotting practice", "Mnemonics & memory aids", "Mock-test generator", "Self-quiz me"],
        note: "Produce revision material. For practice questions, prompt the student to attempt FIRST, then give the model answer with marking pointers."
    ),
    RoleCard(
        id: "skills-practice", role: .student,
        title: "Skills Practice",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["law-student", "moot"],
        dropdown: ["Draft-a-document tutorial (walk-through)", "Model document (for study)", "Critique my draft", "Legal-writing feedback", "IRAC / issue-analysis coach", "Client-interview / negotiation roleplay"],
        note: "Learn by doing. A model document must be clearly labelled a STUDY EXAMPLE and end with a \"now try your own\" prompt. For critiques, give specific feedback — do NOT rewrite the whole thing."
    ),
    RoleCard(
        id: "moot-court", role: .student,
        title: "Moot Court & Advocacy",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["moot"],
        dropdown: ["Memorial / memo structure & feedback", "Argument builder (both sides)", "Rebuttal practice", "Authority / compilation help", "Oral-round Q&A drills", "Judge-style questioning"],
        note: "Coach both sides. Build arguments, drill rebuttals and pose judge-style questions for the student to answer rather than answering for them."
    ),
    RoleCard(
        id: "research-writing", role: .student,
        title: "Research & Writing",
        subtitle: nil,
        section: nil,
        output: .research,
        isSafetyFirst: false,
        filters: ["research", "law-student"],
        dropdown: ["Research-question framing", "Source & authority finder", "Literature-map / outline", "Citation formatting (Bluebook / OSCOLA / journal)", "Argument-structure feedback", "Plagiarism-risk & originality guidance", "Abstract / synopsis feedback"],
        note: "Guide the research and writing process; give citations in the requested style and flag plagiarism/originality risk. Do NOT write the paper — coach the student to write it."
    ),
    RoleCard(
        id: "career-prep", role: .student,
        title: "Career & Practical Prep",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["law-student"],
        dropdown: ["Internship-application / CV feedback", "Practical-lawyering explainer", "Court / procedure walkthrough", "Exam-prep guidance (judiciary / bar)", "Legal-CV & cover letter"],
        note: "Give practical, encouraging guidance. For CV / cover letters, provide a model plus specific feedback the student can act on."
    ),
    RoleCard(
        id: "doc-prep", role: .paralegal,
        title: "Document Preparation",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["general", "litigation", "corporate"],
        dropdown: ["Vakalatnama", "Memo of parties", "Affidavit / verification", "Index / list of documents", "List of dates & events", "Forwarding / cover letter", "Certified-copy application", "Authorising board resolution", "Power of attorney"],
        note: "Prepare the routine document in standard Indian format, with clearly marked [placeholders] for party, matter and date specifics."
    ),
    RoleCard(
        id: "court-filing", role: .paralegal,
        title: "Court Filing & Procedure",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["litigation", "general"],
        dropdown: ["Filing checklist (by court / matter type)", "Court-fee & stamp-duty calculator", "e-Filing preparation pack", "Limitation / deadline calculator", "Jurisdiction / correct-forum checker", "Defect / registry-objection response prep"],
        note: "For fee / limitation / jurisdiction tasks, show the working (computation or checklist) and cite the governing rule or court practice. The advocate must verify before filing."
    ),
    RoleCard(
        id: "case-mgmt", role: .paralegal,
        title: "Case & Cause-List Management",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["litigation", "general"],
        dropdown: ["Hearing-date tracker", "Cause-list monitor note", "Matter diary", "Limitation tracker", "Next-step / task checklist", "Status-update note (client / lawyer)"],
        note: "Produce an organised tracker / diary / checklist. Administrative and organisational only — take no view on the merits."
    ),
    RoleCard(
        id: "doc-review", role: .paralegal,
        title: "Document Review & Summarising",
        subtitle: nil,
        section: nil,
        output: .research,
        isSafetyFirst: false,
        filters: ["general", "litigation", "corporate"],
        dropdown: ["Document summary", "Deposition / evidence digest", "Contract summary (for review)", "Chronology builder", "Key-fact / key-clause extraction", "Comparison of two drafts"],
        note: "Neutral summary / extraction to support the lawyer's review. Do not opine on merits or give advice; flag anything needing the advocate's judgement."
    ),
    RoleCard(
        id: "research-support", role: .paralegal,
        title: "Legal Research Support",
        subtitle: nil,
        section: nil,
        output: .research,
        isSafetyFirst: false,
        filters: ["general", "litigation", "corporate"],
        dropdown: ["Case-law lookup", "Statutory / bare-act provision pull", "Citation finder & verification", "Precedent gathering", "\"Is it still good law?\" flag (for lawyer to confirm)"],
        note: "Basic research for the lawyer to verify. Give real, verifiable citations and flag good-law status \"[for supervising advocate to confirm]\". Do not draw legal conclusions."
    ),
    RoleCard(
        id: "bundle", role: .paralegal,
        title: "Bundle / Paperbook Compilation",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["litigation"],
        dropdown: ["Index & pagination", "Paperbook / brief compilation", "Exhibit list", "Compilation of authorities", "Convenience / common compilation"],
        note: "Compile the index / paperbook / exhibit list in the court's required format with correct, consistent pagination."
    ),
    RoleCard(
        id: "intake", role: .paralegal,
        title: "Client Intake & Coordination",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["general", "corporate"],
        dropdown: ["Document-collection checklist", "KYC / client-info form", "Engagement / retainer letter (draft)", "Intake questionnaire", "Follow-up / reminder drafts"],
        note: "Prepare the intake / KYC / engagement document as a fillable draft with [placeholders]. Engagement / retainer letters are drafts for the advocate to settle."
    ),
    RoleCard(
        id: "correspondence", role: .paralegal,
        title: "Correspondence & Notices",
        subtitle: nil,
        section: nil,
        output: .document,
        isSafetyFirst: false,
        filters: ["general", "litigation"],
        dropdown: ["Routine letter draft", "RTI application", "Reminder / follow-up letter", "Acknowledgement draft", "Email to registry / opposing counsel"],
        note: "Draft the routine letter / application / email in a professional register with [placeholders]. Routine correspondence only — not a legal notice asserting rights unless the advocate directs."
    ),
    RoleCard(
        id: "safety-first", role: .legalAid,
        title: "Safety First",
        subtitle: "Helpline + human referral before any drafting",
        section: "Safety First",
        output: .document,
        isSafetyFirst: true,
        filters: ["beneficiary"],
        dropdown: ["Crisis helpline lookup", "Immediate-safety checklist", "Human-referral prompt", "Protection-order fast-track info"],
        note: "SAFETY FIRST. Before any form-filling, surface the relevant crisis helplines and a human referral (DLSA / panel lawyer / shelter). Keep language calm, simple and supportive and prioritise the person's immediate safety over paperwork."
    ),
    RoleCard(
        id: "intake", role: .legalAid,
        title: "Client Intake & Eligibility",
        subtitle: nil,
        section: "Client Intake & Eligibility",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary"],
        dropdown: ["Intake questionnaire", "Legal-aid eligibility check (Sec. 12, LSA Act 1987)", "Issue identification", "Urgency / risk triage", "Consent & confidentiality form"],
        note: "Intake support only. Check legal-aid eligibility against Sec. 12, Legal Services Authorities Act 1987; flag urgency / risk and route any sensitive matter to Safety-First."
    ),
    RoleCard(
        id: "know-your-rights", role: .legalAid,
        title: "Know Your Rights",
        subtitle: nil,
        section: "Know Your Rights",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary"],
        dropdown: ["Explain my rights (topic-wise)", "Government-scheme finder", "Entitlement checklist", "Simple \"what to do next\" steps", "Regional-language explainer"],
        note: "Plain-language rights explainer. Keep it simple and practical, list concrete next steps and point to relevant government schemes."
    ),
    RoleCard(
        id: "applications", role: .legalAid,
        title: "Application & Form Assistance",
        subtitle: nil,
        section: "Application & Form Assistance",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary"],
        dropdown: ["Legal-aid application (DLSA)", "Welfare-scheme application", "Domestic-violence protection (PWDVA 2005)", "Maintenance application (BNSS 144)", "Victim-compensation claim (NALSA scheme)", "Pension / ration / disability / compensation forms"],
        note: "Prepare the application / form as a fillable draft with [placeholders]. Cite the governing scheme / provision and anonymise sensitive personal data."
    ),
    RoleCard(
        id: "complaints", role: .legalAid,
        title: "Complaints & Basic Notices",
        subtitle: nil,
        section: "Complaints & Basic Notices",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary"],
        dropdown: ["Police complaint / FIR request", "RTI application (RTI Act 2005)", "Consumer complaint", "Grievance / representation to authority", "Domestic-incident report support"],
        note: "Draft the routine complaint / application in simple language with [placeholders]."
    ),
    RoleCard(
        id: "referral", role: .legalAid,
        title: "Referral & Escalation",
        subtitle: nil,
        section: "Referral & Escalation",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary"],
        dropdown: ["DLSA / SLSA referral", "Helpline directory (women / child / labour / senior citizen)", "Shelter / support-service referral", "Refer to panel lawyer", "Lok Adalat referral"],
        note: "Provide the appropriate referral / helpline directory. Support and signposting only."
    ),
    RoleCard(
        id: "pil", role: .legalAid,
        title: "PIL & Representations",
        subtitle: nil,
        section: "PIL & Representations",
        output: .document,
        isSafetyFirst: false,
        filters: ["advocacy"],
        dropdown: ["PIL drafting support", "Representation to authority", "Policy / memorandum submission", "Fact-finding report", "Public-interest notice"],
        note: "PIL / representation drafting SUPPORT for the advocate to settle. Emphasise the public interest, maintainability and relevant constitutional provisions."
    ),
    RoleCard(
        id: "awareness", role: .legalAid,
        title: "Awareness & Legal Education",
        subtitle: nil,
        section: "Awareness & Legal Education",
        output: .document,
        isSafetyFirst: false,
        filters: ["advocacy"],
        dropdown: ["Know-your-rights leaflet", "Workshop / legal-literacy camp material", "FAQ on a law / right", "Plain-language poster", "Regional-language content", "Read-aloud script"],
        note: "Legal-education material in plain language, suitable for leaflets / posters / workshops. Provide a regional-language and read-aloud version where asked."
    ),
    RoleCard(
        id: "ngo-compliance", role: .legalAid,
        title: "NGO Compliance & Governance",
        subtitle: nil,
        section: "NGO Compliance & Governance",
        output: .document,
        isSafetyFirst: false,
        filters: ["advocacy"],
        dropdown: ["Society / Trust / Sec-8 registration", "FCRA 2010 compliance", "12A / 80G application", "Annual returns & board minutes", "Grant-compliance checklist", "Donor / partner MoU"],
        note: "NGO compliance / governance document per the relevant law (Societies / Trust / Sec-8, FCRA 2010, 12A / 80G, Income-tax)."
    ),
    RoleCard(
        id: "case-doc", role: .legalAid,
        title: "Case Documentation & Impact",
        subtitle: nil,
        section: "Case Documentation & Impact",
        output: .document,
        isSafetyFirst: false,
        filters: ["advocacy"],
        dropdown: ["Case-documentation template", "Outcome / impact tracker", "Beneficiary register (anonymised)", "Donor / grant report support", "Camp / clinic activity log"],
        note: "Documentation / tracking template. Anonymise beneficiary data by default."
    ),
    RoleCard(
        id: "research", role: .legalAid,
        title: "Legal Research Support",
        subtitle: nil,
        section: "Legal Research Support",
        output: .research,
        isSafetyFirst: false,
        filters: ["beneficiary", "advocacy"],
        dropdown: ["Bare-act / provision lookup", "Case-law lookup", "Scheme / notification finder", "Citation verification (flag for lawyer)"],
        note: "Basic research for the lawyer to verify — bare-act / case-law / scheme lookup with real citations. Flag good-law status \"[for lawyer to confirm]\"."
    ),
    RoleCard(
        id: "language", role: .legalAid,
        title: "Language & Translation",
        subtitle: nil,
        section: "Language & Translation",
        output: .document,
        isSafetyFirst: false,
        filters: ["beneficiary", "advocacy"],
        dropdown: ["Translate document (EN ↔ regional)", "Plain-language rewrite", "Regional-language explainer"],
        note: "Translate / plain-language rewrite faithfully; preserve meaning and keep it accessible."
    ),
]

/// The filter each role's card grid offers, in the platform's order.
let ROLE_CARD_FILTERS: [PractitionerRole: [RoleCardFilter]] = [
    .adjudicator: [
        RoleCardFilter(id: "judge", label: "Judge"),
        RoleCardFilter(id: "arbitrator", label: "Arbitrator"),
    ],
    .corporateCounsel: [
        RoleCardFilter(id: "GEN", label: "General / All"),
        RoleCardFilter(id: "CORP", label: "Corporate & M&A"),
        RoleCardFilter(id: "PE", label: "Private Equity / VC"),
        RoleCardFilter(id: "BANK", label: "Banking & Finance"),
        RoleCardFilter(id: "CAPM", label: "Capital Markets"),
        RoleCardFilter(id: "FIN", label: "Fintech & Fin-Services Reg."),
        RoleCardFilter(id: "RI", label: "Restructuring / Insolvency"),
        RoleCardFilter(id: "ANTI", label: "Antitrust / Competition"),
        RoleCardFilter(id: "TAX", label: "Tax"),
        RoleCardFilter(id: "DATA", label: "Data Protection"),
        RoleCardFilter(id: "IP", label: "Intellectual Property"),
        RoleCardFilter(id: "TMT", label: "TMT"),
        RoleCardFilter(id: "EMP", label: "Labour & Employment"),
        RoleCardFilter(id: "RE", label: "Real Estate & Constr."),
        RoleCardFilter(id: "PROJ", label: "Projects & Energy"),
        RoleCardFilter(id: "AVI", label: "Aviation / A&D"),
        RoleCardFilter(id: "SHIP", label: "Shipping / Maritime"),
        RoleCardFilter(id: "INS", label: "Insurance"),
        RoleCardFilter(id: "LIFE", label: "Life Sciences / Healthcare"),
        RoleCardFilter(id: "PVT", label: "Private Client"),
        RoleCardFilter(id: "ARB", label: "Arbitration"),
        RoleCardFilter(id: "WCC", label: "White-Collar Crime"),
        RoleCardFilter(id: "WTO", label: "WTO / International Trade"),
        RoleCardFilter(id: "LIT", label: "Litigation"),
    ],
    .student: [
        RoleCardFilter(id: "law-student", label: "Law student"),
        RoleCardFilter(id: "moot", label: "Moot / competition"),
        RoleCardFilter(id: "research", label: "Research scholar"),
    ],
    .paralegal: [
        RoleCardFilter(id: "general", label: "General"),
        RoleCardFilter(id: "litigation", label: "Litigation"),
        RoleCardFilter(id: "corporate", label: "Corporate"),
    ],
    .legalAid: [
        RoleCardFilter(id: "beneficiary", label: "Beneficiary Aid"),
        RoleCardFilter(id: "advocacy", label: "Advocacy & Organisation"),
    ],
]

/// Section order for the roles whose grids are grouped.
let ROLE_CARD_SECTIONS: [PractitionerRole: [String]] = [
    .adjudicator: ["Case File & Record", "Evidence & Analysis", "Research & Language", "Hearing & Administration", "Award & Adjudicatory Drafting", "Costs & Interest", "Judge-Only Tools"],
    .corporateCounsel: ["Drafting — Commercial & General", "Drafting — Corporate, M&A & Investment", "Drafting — Banking, Finance & Capital Markets", "Drafting — Employment & Labour", "Drafting — IP & Technology", "Drafting — Data Protection & Privacy", "Drafting — Real Estate, Construction & Infrastructure", "Drafting — Sector-Specific Commercial", "Advisory, Governance & Compliance", "Private Client", "Disputes"],
    .legalAid: ["Safety First", "Client Intake & Eligibility", "Know Your Rights", "Application & Form Assistance", "Complaints & Basic Notices", "Referral & Escalation", "PIL & Representations", "Awareness & Legal Education", "NGO Compliance & Governance", "Case Documentation & Impact", "Legal Research Support", "Language & Translation"],
]
