import Foundation

/// The legal tools, ported from the platform's own registry.
///
/// ## There is no backend contract here
///
/// A tool on the web is not a server feature. `/w/:toolId` never sends the tool's id anywhere —
/// `ToolWorkspace.jsx` reads it out of the route, looks up a config, and composes the whole
/// framing into the **user message** client-side. The request carries `source: 'chat'`
/// hardcoded, `POST /chat` has no tool field at all, and the system prompt is a function of the
/// role and nothing else.
///
/// So a tool is three pieces of data: a form, a pure function from that form to a prompt, and a
/// hint about how to render the answer. All three belong here, where they are testable without a
/// device and cannot drift into the view layer.
///
/// ## The prompts are the feature, and they are long
///
/// These run to tens of thousands of characters each — the procedural checklists *are* the
/// value, not padding. They are pinned by golden fixtures generated by running the platform's
/// own JavaScript, because a retyped checklist with one dropped clause is a tool that quietly
/// stops covering the objection it exists to catch.

/// How a field is entered.
enum ToolFieldType: String, Sendable {
    case text, textarea, select
}

/// One question a tool asks before it runs.
///
/// Almost nothing is required. The platform made the same choice deliberately: these tools work
/// off an attached record, and a form that insists on being filled first turns a one-tap
/// analysis into data entry.
struct ToolField: Identifiable, Sendable {
    let key: String
    let label: String
    let type: ToolFieldType
    var required: Bool = false
    var placeholder: String?
    /// Only for `.select`.
    var options: [String] = []
    /// A textarea that should be given real height — the one the record gets pasted into.
    var big: Bool = false

    var id: String { key }
}

/// What kind of answer the tool produces.
///
/// Carried through because it changes what the answer *is*, not just how it looks. The
/// platform's own note on Devil's Advocate is the example: rendering an adversarial critique of
/// the user's own draft as a `document` would put Ready-to-File affordances on it, which is
/// actively misleading.
enum ToolOutput: String, Sendable {
    case document, riskReport, timeline, comparison, research, assistant
}

/// The answers, with the defaulting the prompts rely on.
///
/// The platform's templates are written as `${v.forum || 'as the record indicates'}` throughout —
/// the fallback is part of the instruction, not an error path, and several of them tell the model
/// to work the value out from the record instead. So a missing answer must produce that exact
/// fallback text rather than an empty string.
struct ToolValues: Sendable {
    private let values: [String: String]

    init(_ values: [String: String] = [:]) {
        self.values = values
    }

    static let empty = ToolValues()

    /// The value for `key`, trimmed, or `nil` when absent or blank. Drives the optional blocks.
    func raw(_ key: String) -> String? {
        guard let value = values[key]?.trimmingCharacters(in: .whitespacesAndNewlines),
              !value.isEmpty
        else { return nil }
        return value
    }

    /// The value for `key`, or `fallback` when it is absent or blank.
    func text(_ key: String, _ fallback: String) -> String { raw(key) ?? fallback }

    /// Whether the user actually answered `key`.
    func has(_ key: String) -> Bool { raw(key) != nil }
}

/// A tool: a form, a prompt builder, and a rendering hint.
struct ToolSpec: Identifiable, Sendable {
    let id: String
    let title: String
    /// A few words for a list row.
    let short: String
    /// One sentence describing what it does, shown above the form.
    let blurb: String
    let output: ToolOutput
    let inputs: [ToolField]
    /// Pure. Given the answers and today's date, returns the opening user message.
    ///
    /// `today` is a parameter rather than a call to the clock because one tool computes
    /// deadlines against it — Caseflow prints "as on DD.MM.YYYY" and counts days left — and a
    /// prompt builder that reads the wall clock cannot be tested for what it says on a given
    /// day. Most tools ignore it.
    let build: @Sendable (ToolValues, Date) -> String

    /// The prompt for these answers, as of `today`.
    func prompt(_ values: ToolValues, today: Date = Date()) -> String {
        build(values, today)
    }
}

/// The forum list every tool's dropdown offers.
///
/// The platform keeps a hand-copied duplicate of this inside each tool definition, with a comment
/// explaining that importing it from `registry.js` is a real ESM cycle rather than a theoretical
/// one. That constraint does not exist here, so it is declared once.
let FORUMS: [String] = [
    "Supreme Court of India",
    "High Court",
    "District Court",
    "NCLT",
    "NCLAT",
    "NCDRC / Consumer",
    "Arbitral Tribunal",
    "Other Tribunal",
]

/// Formats a date the way the prompts do: `DD.MM.YYYY`, in India.
///
/// Every court date in this product means a day in India, and a tool that prints "as on" against
/// the device's zone tells someone travelling the wrong day.
enum ToolDate {
    static func indianFormat(_ date: Date) -> String {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "Asia/Kolkata") ?? .gmt
        let parts = calendar.dateComponents([.day, .month, .year], from: date)
        return String(format: "%02d.%02d.%04d", parts.day ?? 1, parts.month ?? 1, parts.year ?? 1970)
    }
}
