import Foundation

/// The page-ordering language behind Rearrange: `last, 1-4, 9-7, 2x3`.
///
/// A port of the platform's `src/lib/pageOrder.js`, held to it by `PageOrderGoldenTests`, whose
/// fixture is generated by running that file under Node (`scripts/generate-file-tool-fixtures.mjs`).
///
/// ## Why this is not `PageRanges`
///
/// `PageRanges` answers "which pages do I want?", so it collects into a set and sorts. That is
/// right for Split and wrong here, where the question is "in what order?". A set silently drops
/// the second 5 in `5, 5, 5`, and a sort silently rewrites `9-1` as `1-9` — both the tool quietly
/// overruling an explicit instruction (`pageOrder.js:3-17`). So, deliberately:
///
/// - **Order is never changed.** Tokens are expanded left to right and concatenated.
/// - **A descending range is honoured**: `9-7` counts down.
/// - **Duplicates survive**: `5, 5, 5` is three copies of page 5, and `5x3` is its shorthand.
///
/// ## The grammar (`pageOrder.js:19-28`)
///
/// Tokens separated by commas or newlines, case-insensitive, whitespace-tolerant: `5`, `3-7`,
/// `3..7`, `3 to 7`, `7-3`, `5x3`, `5*3`, `3-7x2`, `all`, `reverse` (or `rev`), `odd`, `even`,
/// `first`, `last`.
///
/// Hand-parsed rather than built on `NSRegularExpression`, because the two engines disagree on
/// exactly the characters that matter: ICU's `\d` matches every Unicode digit where JavaScript's
/// matches `0-9` only, and the two `\s` sets differ (JavaScript counts U+FEFF and vertical tab,
/// ICU counts neither). A page typed in Arabic-Indic digits must be refused here as it is on the
/// web, not quietly accepted.
enum PageOrder {

    /// A single instruction may not expand past this many pages (`pageOrder.js:32-34`). Without
    /// it, `all x2000` on a long brief would ask the phone to build a document it cannot hold.
    static let maxOutputPages = 5000

    struct Parsed: Equatable, Sendable {
        /// The output order, 1-based, direction and duplicates preserved.
        var pages: [Int]
        /// Human-readable problems. `pages` holds whatever parsed cleanly, so a half-typed
        /// instruction still previews.
        var errors: [String]
        /// Source pages that appear nowhere in `pages`, ascending — sorted because it is a
        /// report, not an order.
        var dropped: [Int]
    }

    /// Never throws: a bad token is reported and skipped, so the preview can follow the user's
    /// typing (`pageOrder.js:30-31`).
    static func parse(_ spec: String?, pageCount: Int) -> Parsed {
        var pages: [Int] = []
        var errors: [String] = []
        guard pageCount >= 1 else { return Parsed(pages: [], errors: [], dropped: []) }

        tokens: for raw in splitTokens(spec ?? "") {
            let token = jsTrim(raw)
            guard !token.isEmpty else { continue }

            guard let match = Token(token) else {
                errors.append(
                    "\"\(token)\" is not something I understand — try 5, 3-7, 9-7, 5x3, all, "
                        + "reverse, odd, even, first or last.")
                continue
            }

            let expanded: [Int]
            switch match.base.expand(pageCount: pageCount) {
            case .pages(let list):
                expanded = list
            case .outOfRange(let first, let last):
                let which = first.value == last.value
                    ? "Page \(first.text)" : "Pages \(first.text)-\(last.text)"
                errors.append(
                    "\(which): this document only has \(pageCount) page\(pageCount > 1 ? "s" : "").")
                continue
            }

            // `parseInt` of an absent group is no repeat at all; of a present one, a number that
            // may be far past any integer type, which is why this stays a Double like the
            // JavaScript it ports.
            let repeatCount = match.repeatCount?.value ?? 1
            if repeatCount < 1 {
                errors.append("\"\(token)\": a repeat count has to be 1 or more.")
                continue
            }
            if Double(pages.count) + Double(expanded.count) * repeatCount > Double(maxOutputPages) {
                // The web's sentence says "in the browser". Kept as the meaning, not the words:
                // there is no browser here.
                errors.append(
                    "That would produce more than \(maxOutputPages) pages, which is more than "
                        + "this tool will build on the phone.")
                // Stops reading further tokens, as `pageOrder.js:113` does.
                break tokens
            }
            // An empty expansion (`even` on a one-page document) repeated is still empty. The
            // JavaScript loops `repeat` times regardless, which for a huge count never returns;
            // skipping the loop gives the same result without the hang.
            guard !expanded.isEmpty else { continue }
            for _ in 0..<Int(repeatCount) { pages.append(contentsOf: expanded) }
        }

        let seen = Set(pages)
        let dropped = (1...pageCount).filter { !seen.contains($0) }
        return Parsed(pages: pages, errors: errors, dropped: dropped)
    }

    /// The inverse: the shortest instruction that produces exactly `pages`.
    ///
    /// Used when the preview's chips are edited by hand, so the text field and the preview are
    /// two views of one value and can never disagree (`pageOrder.js:125-152`). Repeats collapse
    /// to `5x3`; runs of three or more in either direction collapse to `3-5` or `9-7`; a pair
    /// stays as `1, 2`, which is shorter to read than a range and harder to misread.
    static func format(_ pages: [Int]) -> String {
        var parts: [String] = []
        var index = 0
        while index < pages.count {
            var repeats = 1
            while index + repeats < pages.count, pages[index + repeats] == pages[index] {
                repeats += 1
            }
            if repeats >= 2 {
                parts.append("\(pages[index])x\(repeats)")
                index += repeats
                continue
            }

            if index + 1 < pages.count {
                let step = pages[index + 1] - pages[index]
                if step == 1 || step == -1 {
                    var length = 1
                    while index + length < pages.count,
                          pages[index + length] - pages[index + length - 1] == step {
                        length += 1
                    }
                    if length >= 3 {
                        parts.append("\(pages[index])-\(pages[index + length - 1])")
                        index += length
                        continue
                    }
                }
            }
            parts.append("\(pages[index])")
            index += 1
        }
        return parts.joined(separator: ", ")
    }

    /// `3, 4, 5, 9` → `3-5, 9`, for the "these pages will not appear" notice
    /// (`RearrangePdf.jsx:365`). Only ever given the ascending `dropped` list, which is a report
    /// rather than an order, so collapsing runs loses nothing. Unlike `format`, a pair stays as
    /// two numbers and a run needs three.
    static func summarise(_ ascending: [Int]) -> String {
        var parts: [String] = []
        var start = 0
        while start < ascending.count {
            var end = start
            while end + 1 < ascending.count, ascending[end + 1] == ascending[end] + 1 { end += 1 }
            if end - start >= 2 {
                parts.append("\(ascending[start])-\(ascending[end])")
            } else {
                parts.append(ascending[start...end].map(String.init).joined(separator: ", "))
            }
            start = end + 1
        }
        return parts.joined(separator: ", ")
    }

    /// The instruction a freshly opened document starts from: every page, as it is.
    ///
    /// Seeded rather than blank, because a blank box on a rearrange tool reads as "type the
    /// pages you want to keep" — Split's question, not this one (`RearrangePdf.jsx:131-135`).
    static func identity(pageCount: Int) -> String {
        pageCount > 1 ? "1-\(pageCount)" : "1"
    }

    // MARK: - Worked examples

    /// One-tap fills, led by the two cases that separate this tool from Split — a descending
    /// range and a duplicated page — because those are what a user would assume impossible
    /// (`RearrangePdf.jsx:104-112`).
    struct Example: Equatable, Sendable, Identifiable {
        let label: String
        /// With `{n}` for the page count and `{prev}` for the one before it.
        let template: String
        let why: String
        var id: String { label }

        func spec(pageCount: Int) -> String {
            // `String.replace` with a string pattern replaces the first occurrence only, which
            // is what the web does; each placeholder appears at most once.
            replacingFirst("{prev}", with: "\(max(1, pageCount - 1))",
                           in: replacingFirst("{n}", with: "\(pageCount)", in: template))
        }

        private func replacingFirst(_ target: String, with value: String, in text: String) -> String {
            guard let range = text.range(of: target) else { return text }
            return text.replacingCharacters(in: range, with: value)
        }
    }

    static let examples: [Example] = [
        Example(label: "Last page first", template: "last, 1-{prev}",
                why: "Move the final page to the front, everything else after it."),
        Example(label: "Duplicate page 1", template: "1x3, 2-{n}",
                why: "Three copies of page 1, then the rest of the document."),
        Example(label: "Reverse everything", template: "reverse",
                why: "Count down from the last page to the first."),
        Example(label: "Odd, then even", template: "odd, even",
                why: "Re-interleave a document scanned in two passes."),
    ]

    // MARK: - Tokens

    /// A number as JavaScript's `parseInt` would hold it: a Double, plus the text JavaScript
    /// would print for it in a message.
    struct Number: Equatable, Sendable {
        let value: Double
        let text: String

        init(digits: Substring) {
            let significant = digits.drop { $0 == "0" }
            if significant.isEmpty {
                value = 0
                text = "0"
            } else if significant.count <= 15 {
                // Fifteen digits are always exact in a Double, so the text is the digits.
                value = Double(String(significant)) ?? 0
                text = String(significant)
            } else {
                value = Double(String(significant)) ?? .infinity
                text = PageOrder.javaScriptString(value)
            }
        }

        /// The value as a page number, when it is one this document could have.
        var page: Int? { value >= 1 && value <= Double(Int32.max) ? Int(value) : nil }
    }

    enum Base: Equatable, Sendable {
        case all, reverse, odd, even, first, last
        case single(Number)
        case span(Number, Number)

        enum Expansion: Equatable {
            case pages([Int])
            case outOfRange(Number, Number)
        }

        func expand(pageCount: Int) -> Expansion {
            switch self {
            case .all: return .pages(Array(1...pageCount))
            case .reverse: return .pages(Array((1...pageCount).reversed()))
            case .odd: return .pages((1...pageCount).filter { $0 % 2 == 1 })
            case .even: return .pages((1...pageCount).filter { $0 % 2 == 0 })
            case .first: return .pages([1])
            case .last: return .pages([pageCount])
            case .single(let number):
                guard let page = number.page, page <= pageCount else {
                    return .outOfRange(number, number)
                }
                return .pages([page])
            case .span(let from, let to):
                guard let start = from.page, let end = to.page,
                      start <= pageCount, end <= pageCount
                else { return .outOfRange(from, to) }
                // The one line the module exists for: the direction the user wrote is the
                // direction they get. No swap, no sort.
                return .pages(start <= end ? Array(start...end) : Array((end...start).reversed()))
            }
        }
    }

    /// One token, matched the way `pageOrder.js:36`'s `TOKEN` regex matches it.
    struct Token: Equatable, Sendable {
        let base: Base
        let repeatCount: Number?

        init?(_ text: String) {
            let scalars = Array(text.unicodeScalars)
            guard !scalars.isEmpty else { return nil }
            // Each alternative is tried in the regex's own order. Only `reverse`/`rev` overlap,
            // and the remainder after either must still be a valid repeat suffix, so trying
            // them in order and keeping the first full match is exactly what backtracking does.
            for (word, base) in Self.keywords {
                if let end = Self.matchKeyword(word, in: scalars, at: 0),
                   let suffix = Self.matchSuffix(in: scalars, at: end) {
                    self.init(base: base, repeatCount: suffix)
                    return
                }
            }
            guard let (base, end) = Self.matchNumberBase(in: scalars) else { return nil }
            guard let suffix = Self.matchSuffix(in: scalars, at: end) else { return nil }
            self.init(base: base, repeatCount: suffix)
        }

        private init(base: Base, repeatCount: Number?) {
            self.base = base
            self.repeatCount = repeatCount
        }

        private static let keywords: [(String, Base)] = [
            ("all", .all), ("reverse", .reverse), ("rev", .reverse), ("odd", .odd),
            ("even", .even), ("first", .first), ("last", .last),
        ]

        /// The `i` flag outside unicode mode folds ASCII letters only, so `ſ` is not `s` and the
        /// Kelvin sign is not `k`.
        private static func matchKeyword(
            _ word: String, in scalars: [Unicode.Scalar], at start: Int
        ) -> Int? {
            var index = start
            for expected in word.unicodeScalars {
                guard index < scalars.count, asciiLower(scalars[index]) == expected else {
                    return nil
                }
                index += 1
            }
            return index
        }

        /// `\d+(?:\s*(?:-|\.\.|to)\s*\d+)?`
        private static func matchNumberBase(in scalars: [Unicode.Scalar]) -> (Base, Int)? {
            guard let (first, afterFirst) = digits(in: scalars, at: 0) else { return nil }

            // The optional span. If it is present but the rest of the token then fails, the
            // regex would retry without it — but the character after the first number would
            // then be a separator, which no suffix accepts, so that retry can never succeed and
            // is not attempted.
            var index = skipWhitespace(in: scalars, at: afterFirst)
            var separatorEnd: Int?
            if index < scalars.count, scalars[index] == "-" {
                separatorEnd = index + 1
            } else if index + 1 < scalars.count, scalars[index] == ".", scalars[index + 1] == "." {
                separatorEnd = index + 2
            } else if index + 1 < scalars.count,
                      asciiLower(scalars[index]) == "t", asciiLower(scalars[index + 1]) == "o" {
                separatorEnd = index + 2
            }
            if let separatorEnd {
                index = skipWhitespace(in: scalars, at: separatorEnd)
                if let (second, afterSecond) = digits(in: scalars, at: index),
                   matchSuffix(in: scalars, at: afterSecond) != nil {
                    return (.span(Number(digits: first), Number(digits: second)), afterSecond)
                }
            }
            return (.single(Number(digits: first)), afterFirst)
        }

        /// `(?:\s*[x*]\s*(\d+))?$` — `.some(nil)` for no repeat, `nil` for no match.
        private static func matchSuffix(in scalars: [Unicode.Scalar], at start: Int) -> Number?? {
            if start == scalars.count { return .some(nil) }
            var index = skipWhitespace(in: scalars, at: start)
            guard index < scalars.count,
                  asciiLower(scalars[index]) == "x" || scalars[index] == "*"
            else { return nil }
            index = skipWhitespace(in: scalars, at: index + 1)
            guard let (count, end) = digits(in: scalars, at: index), end == scalars.count else {
                return nil
            }
            return .some(Number(digits: count))
        }

        private static func digits(
            in scalars: [Unicode.Scalar], at start: Int
        ) -> (Substring, Int)? {
            var end = start
            while end < scalars.count, ("0"..."9").contains(scalars[end]) { end += 1 }
            guard end > start else { return nil }
            var text = ""
            text.unicodeScalars.append(contentsOf: scalars[start..<end])
            return (Substring(text), end)
        }

        private static func skipWhitespace(in scalars: [Unicode.Scalar], at start: Int) -> Int {
            var index = start
            while index < scalars.count, PageOrder.isJavaScriptWhitespace(scalars[index]) {
                index += 1
            }
            return index
        }

        private static func asciiLower(_ scalar: Unicode.Scalar) -> Unicode.Scalar {
            ("A"..."Z").contains(scalar) ? Unicode.Scalar(scalar.value + 32)! : scalar
        }
    }

    // MARK: - JavaScript's idea of whitespace and of a number

    /// What `String.prototype.trim` strips and `\s` matches: ECMAScript's WhiteSpace plus
    /// LineTerminator. Not Foundation's `.whitespacesAndNewlines`, which also takes U+0085 —
    /// a character the web reports as an error rather than ignoring.
    static func isJavaScriptWhitespace(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.value {
        case 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0xA0, 0x1680, 0x2000...0x200A,
             0x2028, 0x2029, 0x202F, 0x205F, 0x3000, 0xFEFF:
            return true
        default:
            return false
        }
    }

    static func jsTrim(_ scalars: [Unicode.Scalar]) -> String {
        guard let first = scalars.firstIndex(where: { !isJavaScriptWhitespace($0) }),
              let last = scalars.lastIndex(where: { !isJavaScriptWhitespace($0) })
        else { return "" }
        var trimmed = ""
        trimmed.unicodeScalars.append(contentsOf: scalars[first...last])
        return trimmed
    }

    /// `split(/[,\n]/)`, on scalars rather than `Character`s. Swift reads `\r\n` as one
    /// character, so splitting characters on `\n` would never separate a pasted Windows line —
    /// where JavaScript splits it and then trims the `\r` away.
    private static func splitTokens(_ text: String) -> [[Unicode.Scalar]] {
        var tokens: [[Unicode.Scalar]] = [[]]
        for scalar in text.unicodeScalars {
            if scalar == "," || scalar == "\n" {
                tokens.append([])
            } else {
                tokens[tokens.count - 1].append(scalar)
            }
        }
        return tokens
    }

    /// `Number.prototype.toString` for a non-negative whole number: the shortest digits that
    /// round-trip, written out in full below 10²¹ and in exponent form from there.
    ///
    /// Only reached for a page number longer than fifteen digits, which nobody types on purpose —
    /// but the error message quotes it, and the port should say what the web says.
    static func javaScriptString(_ value: Double) -> String {
        guard value.isFinite else { return "Infinity" }
        // Swift's description is also shortest-round-trip; only its layout differs.
        let description = "\(value)"
        let parts = description.lowercased().split(separator: "e")
        let mantissa = parts[0]
        let exponent = parts.count > 1 ? Int(parts[1]) ?? 0 : 0
        let pieces = mantissa.split(separator: ".", omittingEmptySubsequences: false)
        let whole = String(pieces[0])
        var fraction = pieces.count > 1 ? String(pieces[1]) : ""
        while fraction.hasSuffix("0") { fraction.removeLast() }

        var digits = (whole + fraction).drop { $0 == "0" }
        while digits.hasSuffix("0") { digits.removeLast() }
        guard !digits.isEmpty else { return "0" }
        // Position of the decimal point after the first significant digit, as ECMAScript's `n`.
        let leadingZeros = (whole + fraction).prefix { $0 == "0" }.count
        let n = whole.count + exponent - leadingZeros
        let k = digits.count

        if k <= n && n <= 21 {
            return String(digits) + String(repeating: "0", count: n - k)
        }
        let sign = n - 1 >= 0 ? "+" : "-"
        let rest = digits.dropFirst()
        return "\(digits.first!)\(rest.isEmpty ? "" : ".\(rest)")e\(sign)\(abs(n - 1))"
    }
}
