// Generated by scripts/generate-record-tokens.mjs from Design/record-tokens.json.
// Do not edit by hand: change the JSON and regenerate.

import Foundation

/// The Record design tokens — "Emperor Record — mobile", v1.0.0 (2026-10-10).
///
/// The iOS value of every platform-split token. Colours are `PaletteColor` so the contrast of
/// every pairing can be tested here, without a device; `Palette` and `Theme` are built on them.
enum RecordTokens {

    static let version = "1.0.0"

    // MARK: - Colour

    /// One appearance's colour roles, named as the design names them.
    struct ColorSet: Equatable, Sendable {
        let bg: PaletteColor
        let surface: PaletteColor
        let surface2: PaletteColor
        let elevated: PaletteColor
        let hover: PaletteColor
        let press: PaletteColor
        let border: PaletteColor
        let borderStrong: PaletteColor
        let text: PaletteColor
        let textSoft: PaletteColor
        let textFaint: PaletteColor
        let textMute: PaletteColor
        let accent: PaletteColor
        let accent2: PaletteColor
        let accentSoft: PaletteColor
        let accentLine: PaletteColor
        let onAccent: PaletteColor
        let mark: PaletteColor
        let bubble: PaletteColor
        let chrome: PaletteColor
        let chromeTint: PaletteColor
        let inverse: PaletteColor
        let onInverse: PaletteColor
        let scrim: PaletteColor
        let paper: PaletteColor
        let paperInk: PaletteColor
        let success: PaletteColor
        let successBg: PaletteColor
        let warn: PaletteColor
        let warnBg: PaletteColor
        let danger: PaletteColor
        let dangerBg: PaletteColor
        let switchOff: PaletteColor
    }

    static let light = ColorSet(
        bg: PaletteColor(hex: 0xFFFFFF),
        surface: PaletteColor(hex: 0xFFFFFF),
        surface2: PaletteColor(hex: 0xF7F8FC),
        elevated: PaletteColor(hex: 0xFFFFFF),
        hover: PaletteColor(hex: 0xF2F4FB),
        press: PaletteColor(hex: 0xE9ECF7),
        border: PaletteColor(hex: 0xE8EAF2),
        borderStrong: PaletteColor(hex: 0xD5D9E8),
        text: PaletteColor(hex: 0x0F1424),
        textSoft: PaletteColor(hex: 0x454B63),
        textFaint: PaletteColor(hex: 0x5A6178),
        textMute: PaletteColor(hex: 0x6B7187),
        accent: PaletteColor(hex: 0x464E85),
        accent2: PaletteColor(hex: 0x547592),
        accentSoft: PaletteColor(hex: 0x6F79BD, opacity: 0.12),
        accentLine: PaletteColor(hex: 0x6F79BD, opacity: 0.32),
        onAccent: PaletteColor(hex: 0xFFFFFF),
        mark: PaletteColor(hex: 0x6F79BD, opacity: 0.27),
        bubble: PaletteColor(hex: 0xEEF0F9),
        chrome: PaletteColor(hex: 0xFFFFFF, opacity: 0.84),
        chromeTint: PaletteColor(hex: 0xF4F5FB),
        inverse: PaletteColor(hex: 0x232842),
        onInverse: PaletteColor(hex: 0xEEF0F8),
        scrim: PaletteColor(hex: 0x0F1424, opacity: 0.38),
        paper: PaletteColor(hex: 0xFFFFFF),
        paperInk: PaletteColor(hex: 0x1A1F33),
        success: PaletteColor(hex: 0x1E6B45),
        successBg: PaletteColor(hex: 0x1E6B45, opacity: 0.09),
        warn: PaletteColor(hex: 0x8A5A0B),
        warnBg: PaletteColor(hex: 0xD69824, opacity: 0.14),
        danger: PaletteColor(hex: 0xB42318),
        dangerBg: PaletteColor(hex: 0xB42318, opacity: 0.07),
        switchOff: PaletteColor(hex: 0xD5D9E8))

    static let dark = ColorSet(
        bg: PaletteColor(hex: 0x14172A),
        surface: PaletteColor(hex: 0x1B1F36),
        surface2: PaletteColor(hex: 0x20253F),
        elevated: PaletteColor(hex: 0x232842),
        hover: PaletteColor(hex: 0x262B48),
        press: PaletteColor(hex: 0x2C3253),
        border: PaletteColor(hex: 0x2E3352),
        borderStrong: PaletteColor(hex: 0x3A4066),
        text: PaletteColor(hex: 0xEEF0F8),
        textSoft: PaletteColor(hex: 0xC3C8DD),
        textFaint: PaletteColor(hex: 0xA1A8C3),
        textMute: PaletteColor(hex: 0x8C93B0),
        accent: PaletteColor(hex: 0x8B95CC),
        accent2: PaletteColor(hex: 0x8FB4D3),
        accentSoft: PaletteColor(hex: 0x8B95CC, opacity: 0.16),
        accentLine: PaletteColor(hex: 0x8B95CC, opacity: 0.38),
        onAccent: PaletteColor(hex: 0xFFFFFF),
        mark: PaletteColor(hex: 0x8B95CC, opacity: 0.34),
        bubble: PaletteColor(hex: 0x2E3459),
        chrome: PaletteColor(hex: 0x171A2E, opacity: 0.84),
        chromeTint: PaletteColor(hex: 0x1D2139),
        inverse: PaletteColor(hex: 0xEEF0F8),
        onInverse: PaletteColor(hex: 0x171A2E),
        scrim: PaletteColor(hex: 0x050710, opacity: 0.6),
        paper: PaletteColor(hex: 0x1B1F36),
        paperInk: PaletteColor(hex: 0xE3E6F2),
        success: PaletteColor(hex: 0x5CC28D),
        successBg: PaletteColor(hex: 0x5CC28D, opacity: 0.12),
        warn: PaletteColor(hex: 0xE3B35A),
        warnBg: PaletteColor(hex: 0xE3B35A, opacity: 0.14),
        danger: PaletteColor(hex: 0xF07A6E),
        dangerBg: PaletteColor(hex: 0xF07A6E, opacity: 0.12),
        switchOff: PaletteColor(hex: 0x3A4066))

    // MARK: - Gradients

    /// A two-stop linear gradient. `angle` is CSS degrees: 135 runs top-leading to bottom-trailing.
    struct GradientStops: Equatable, Sendable {
        let start: PaletteColor
        let end: PaletteColor
        let angle: Double
    }

    enum Gradient {
        static let primaryLight = GradientStops(
            start: PaletteColor(hex: 0x464E85), end: PaletteColor(hex: 0x547592), angle: 135)
        static let primaryDark = GradientStops(
            start: PaletteColor(hex: 0x4D568F), end: PaletteColor(hex: 0x5A7C9A), angle: 135)
        static let logoLight = GradientStops(
            start: PaletteColor(hex: 0x6F79BD), end: PaletteColor(hex: 0x6F9AC0), angle: 135)
        static let logoDark = GradientStops(
            start: PaletteColor(hex: 0x9AA3DA), end: PaletteColor(hex: 0x9CC2DE), angle: 135)
    }

    // MARK: - Type

    enum FontRole: Sendable, Equatable {
        /// Instrument Serif — large titles, greetings, item numbers, document titles.
        case display
        /// Plus Jakarta Sans — everything else.
        case ui
    }

    /// One step of the type scale, at the default Dynamic Type size.
    struct TextStyle: Equatable, Sendable {
        let role: FontRole
        /// CSS weight: 400, 500, 600 or 700.
        let weight: Int
        let size: Double
        /// Line height, where the scale gives one.
        let lineHeight: Double?
        /// Letter spacing as a fraction of the size (CSS `em`).
        let tracking: Double
        let uppercase: Bool
    }

    enum Typography {
        static let largeTitle = TextStyle(
            role: .display, weight: 400, size: 36, lineHeight: 39,
            tracking: -0.012, uppercase: false)
        static let title = TextStyle(
            role: .display, weight: 400, size: 26, lineHeight: 30,
            tracking: 0, uppercase: false)
        static let navTitle = TextStyle(
            role: .ui, weight: 600, size: 17, lineHeight: 22,
            tracking: 0, uppercase: false)
        static let body = TextStyle(
            role: .ui, weight: 400, size: 17, lineHeight: 25,
            tracking: 0, uppercase: false)
        static let bodyStrong = TextStyle(
            role: .ui, weight: 600, size: 17, lineHeight: 22,
            tracking: 0, uppercase: false)
        static let callout = TextStyle(
            role: .ui, weight: 500, size: 15, lineHeight: 20,
            tracking: 0, uppercase: false)
        static let footnote = TextStyle(
            role: .ui, weight: 400, size: 13, lineHeight: 18,
            tracking: 0, uppercase: false)
        static let label = TextStyle(
            role: .ui, weight: 700, size: 12, lineHeight: 16,
            tracking: 0.08, uppercase: true)
        static let tab = TextStyle(
            role: .ui, weight: 600, size: 10.5, lineHeight: nil,
            tracking: 0, uppercase: false)
        static let citation = TextStyle(
            role: .ui, weight: 700, size: 11, lineHeight: nil,
            tracking: 0, uppercase: false)
    }

    // MARK: - Shape, space, layout

    enum Radius {
        static let control: Double = 6
        static let card: Double = 8
        static let group: Double = 10
        static let dialog: Double = 14
        static let sheet: Double = 14
        /// Top-leading, top-trailing, bottom-trailing, bottom-leading.
        static let bubble: [Double] = [14, 14, 4, 14]
        static let chip: Double = 999
        static let fab: Double = 16
        static let pill: Double = 999
    }

    enum Space {
        static let xxs: Double = 4
        static let xs: Double = 8
        static let s: Double = 12
        static let m: Double = 16
        static let l: Double = 20
        static let xl: Double = 24
        static let xxl: Double = 32
        static let xxxl: Double = 40
    }

    enum Layout {
        static let gutter: Double = 20
        static let touchTarget: Double = 44
        static let buttonHeight: Double = 50
        static let topBar: Double = 44
        static let tabBar: Double = 49
        static let listRow: Double = 52
        static let composerMaxLines: Int = 6
    }

    // MARK: - Motion

    /// A cubic Bézier timing curve, as CSS `cubic-bezier(x1, y1, x2, y2)`.
    struct Curve: Equatable, Sendable {
        let x1: Double, y1: Double, x2: Double, y2: Double
    }

    enum Motion {
        static let easeOut = Curve(x1: 0.22, y1: 1, x2: 0.36, y2: 1)
        static let easeInOut = Curve(x1: 0.65, y1: 0, x2: 0.35, y2: 1)
        static let easePop = Curve(x1: 0.34, y1: 1.56, x2: 0.64, y2: 1)

        /// Durations, in seconds.
        enum Duration {
            static let tap: Double = 0.12
            static let fade: Double = 0.2
            static let tabFadeThrough: Double = 0.28
            static let androidAxis: Double = 0.3
            static let iosPush: Double = 0.42
            static let sheet: Double = 0.42
            static let readingCardFold: Double = 0.35
            static let stepReveal: Double = 0.85
            /// Reduce Motion: "replace movement with a 150 ms cross-fade; never animate the reading card's scan line".
            static let reduceMotionCrossFade: Double = 0.15
        }
    }

    // MARK: - Elevation

    struct Shadow: Equatable, Sendable {
        let y: Double
        let blur: Double
        let color: PaletteColor
    }

    enum Elevation {
        static let level1 = Shadow(y: 1, blur: 2, color: PaletteColor(hex: 0x0F1424, opacity: 0.06))
        static let level2 = Shadow(y: 8, blur: 24, color: PaletteColor(hex: 0x0F1424, opacity: 0.1))
        static let level3 = Shadow(y: 24, blur: 60, color: PaletteColor(hex: 0x0F1424, opacity: 0.18))
    }
}
